audio_models = []
image_models = ['dall-e-3', 'gpt-image', 'sdxl-turbo', 'sd-3.5-large', 'flux', 'flux-pro', 'flux-kontext', 'black-forest-labs/FLUX-2-klein-4b', 'black-forest-labs/FLUX-2-klein-9b', 'flux-2-klein-4b', 'flux-2-klein-9b', 'sd-3.5-large', 'flux-dev', 'flux', 'flux-kontext-dev', 'sd-3.5-large', 'flux-dev', 'flux', 'flux-kontext-dev']
vision_models = []
video_models = ['video']
model_map = {
  "default": {
    "Qwen": "",
    "TeachAnything": "",
    "GLM": "",
    "KiloCode": "",
    "CopilotApp": "",
    "OpenCode": "",
    "DeepInfra": "",
    "Ollama": "",
    "Pollinations": "",
    "OperaAria": "",
    "GeminiPro": "",
    "OpenRouterFree": "",
    "ChatGPTLightweight": "",
    "LLM7": "default",
    "OpenaiChat": "",
    "G4FSpace": "default:"
  },
  "agent-tools": {
    "AgentTools": "Agent Tools (MCP)"
  },
  "gpt-4": {
    "CopilotApp": "chat",
    "Yqcloud": "gpt-4",
    "OpenaiChat": "gpt-4",
    "Airforce": "gpt-4",
    "Copilot": "Copilot",
    "CopilotAccount": "Copilot",
    "CopilotSession": "Copilot",
    "GithubCopilot": "gpt-4",
    "KiloCode": "openai/gpt-4",
    "OpenRouter": "openai/gpt-4",
    "Puter": "openrouter:openai/gpt-4"
  },
  "gpt-4o": {
    "CopilotApp": "chat",
    "OpenaiChat": "gpt-4o",
    "Airforce": "gpt-4o",
    "Copilot": "Copilot",
    "CopilotAccount": "Copilot",
    "CopilotSession": "Copilot",
    "GithubCopilot": "gpt-4o",
    "KiloCode": "openai/gpt-4o-2024-05-13",
    "OpenRouter": "openai/gpt-4o:batch",
    "ChatGPTLightweight": "gpt-4o",
    "Puter": "openrouter:openai/gpt-4o:batch"
  },
  "gpt-4o-mini": {
    "OpenaiChat": "gpt-4o-mini",
    "ChatGPTLightweight": "gpt-4o-mini",
    "Airforce": "gpt-4o-mini",
    "CopilotApp": "chat",
    "GithubCopilot": "gpt-4o-mini",
    "KiloCode": "openai/gpt-4o-mini-2024-07-18",
    "OpenRouter": "openai/gpt-4o-mini:batch",
    "Puter": "openrouter:openai/gpt-4o-mini:batch"
  },
  "gpt-4o-mini-tts": {
    "OpenAIFM": "coral",
    "Airforce": "gpt-4o-mini-tts"
  },
  "o1": {
    "OpenaiAccount": "o1",
    "Airforce": "o1",
    "Copilot": "Think Deeper",
    "CopilotAccount": "Think Deeper",
    "CopilotApp": "reasoning",
    "CopilotSession": "Think Deeper",
    "KiloCode": "openai/o1",
    "OpenRouter": "openai/o1",
    "OpenaiChat": "o1",
    "Puter": "openrouter:openai/o1"
  },
  "o1-mini": {
    "OpenaiAccount": "o1-mini",
    "Airforce": "o1-mini",
    "OpenaiChat": "o1-mini",
    "Puter": "infron:openai/o1-mini"
  },
  "o3-mini": {
    "OpenaiChat": "o3-mini",
    "Airforce": "o3-mini",
    "CopilotApp": "reasoning",
    "LMArena": "o3-mini",
    "KiloCode": "openai/o3-mini",
    "OpenRouter": "openai/o3-mini:batch",
    "Puter": "openrouter:openai/o3-mini:batch"
  },
  "o3-mini-high": {
    "OpenaiAccount": "o3-mini-high",
    "KiloCode": "openai/o3-mini-high",
    "OpenRouter": "openai/o3-mini-high",
    "OpenaiChat": "o3-mini-high",
    "Puter": "openrouter:openai/o3-mini-high"
  },
  "o4-mini": {
    "OpenaiChat": "o4-mini",
    "Airforce": "o4-mini",
    "LMArena": "o4-mini-2025-04-16",
    "KiloCode": "openai/o4-mini",
    "OpenRouter": "openai/o4-mini:batch",
    "Puter": "openrouter:openai/o4-mini:batch"
  },
  "o4-mini-high": {
    "OpenaiChat": "o4-mini-high",
    "KiloCode": "openai/o4-mini-high",
    "OpenRouter": "openai/o4-mini-high",
    "Puter": "openrouter:openai/o4-mini-high"
  },
  "gpt-4.1": {
    "OpenaiChat": "gpt-4-1",
    "Airforce": "gpt-4.1",
    "GithubCopilot": "gpt-4.1",
    "LMArena": "gpt-4.1-2025-04-14",
    "KiloCode": "openai/gpt-4.1",
    "OpenRouter": "openai/gpt-4.1:batch",
    "Puter": "openrouter:openai/gpt-4.1:batch"
  },
  "gpt-4.1-mini": {
    "OpenaiChat": "gpt-4-1-mini",
    "Airforce": "gpt-4.1-mini",
    "LMArena": "gpt-4.1-mini-2025-04-14",
    "KiloCode": "openai/gpt-4.1-mini",
    "OpenRouter": "openai/gpt-4.1-mini:batch",
    "ChatGPTLightweight": "gpt-4.1-mini",
    "Puter": "openrouter:openai/gpt-4.1-mini:batch"
  },
  "gpt-4.1-nano": {
    "Pollinations": "openai-fast",
    "Airforce": "gpt-4.1-nano",
    "KiloCode": "openai/gpt-4.1-nano",
    "OpenRouter": "openai/gpt-4.1-nano:batch",
    "Puter": "openrouter:openai/gpt-4.1-nano:batch"
  },
  "gpt-4.5": {
    "OpenaiChat": "gpt-4-5",
    "Airforce": "gpt-4.5-preview"
  },
  "gpt-oss-120b": {
    "Together": "openai/gpt-oss-120b",
    "OpenRouter": "openai/gpt-oss-120b:batch",
    "Groq": "openai/gpt-oss-120b",
    "HuggingFace": "openai/gpt-oss-120b",
    "Airforce": "gpt-oss-120b",
    "Cloudflare": "@cf/openai/gpt-oss-120b",
    "G4FSpace": "srv_mkom688d57c76d8a3542:openai/gpt-oss-120b",
    "HuggingChat": "openai/gpt-oss-120b",
    "LMArena": "gpt-oss-120b",
    "KiloCode": "openai/gpt-oss-120b",
    "Ollama": "gpt-oss:120b",
    "Puter": "togetherai:openai/gpt-oss-120b"
  },
  "dall-e-3": {
    "OpenaiAccount": "dall-e-3",
    "MicrosoftDesigner": "dall-e-3",
    "BingCreateImages": "dall-e-3",
    "CopilotAccount": "Copilot",
    "OpenaiChat": "gpt-image"
  },
  "gpt-image": {
    "PollinationsImage": "gpt-image",
    "OpenaiChat": "gpt-image",
    "Pollinations": "gptimage"
  },
  "meta-ai": {
    "MetaAI": "meta-ai",
    "MetaAIAccount": "meta-ai"
  },
  "llama-2-70b": {
    "Together": "llama-2-70b",
    "Airforce": "llama-2-70b",
    "Nvidia": "meta/llama2-70b",
    "Puter": "openrouter:meta-llama/llama-2-70b-chat"
  },
  "llama-3-8b": {
    "Together": "llama-3-8b",
    "Airforce": "llama-3-8b",
    "Cloudflare": "@hf/meta-llama/meta-llama-3-8b-instruct",
    "PerplexityApi": "llama-3-8b-instruct",
    "Puter": "openrouter:meta-llama/llama-3-8b-instruct"
  },
  "llama-3-70b": {
    "Together": "llama-3-70b",
    "Airforce": "llama-3-70b",
    "PerplexityApi": "llama-3-70b-instruct",
    "Puter": "openrouter:meta-llama/llama-3-70b-instruct",
    "Replicate": "meta/meta-llama-3-70b-instruct"
  },
  "llama-3.1-8b": {
    "Together": "llama-3.1-8b",
    "HuggingFace": "meta-llama/Llama-3.1-8B-Instruct",
    "Cerebras": "llama3.1-8b",
    "Cloudflare": "@cf/meta/llama-3.1-8b-instruct-fp8",
    "HuggingChat": "meta-llama/Llama-3.1-8B-Instruct",
    "KiloCode": "meta-llama/llama-3.1-8b-instruct",
    "OpenRouter": "meta-llama/llama-3.1-8b-instruct",
    "Puter": [
      "openrouter:meta-llama/llama-3.1-8b-instruct:free",
      "openrouter:meta-llama/llama-3.1-8b-instruct"
    ]
  },
  "llama-3.1-70b": {
    "Together": "llama-3.1-70b",
    "Cerebras": "llama3.1-70b",
    "KiloCode": "meta-llama/llama-3.1-70b-instruct",
    "OpenRouter": "meta-llama/llama-3.1-70b-instruct",
    "Puter": "openrouter:meta-llama/llama-3.1-70b-instruct"
  },
  "llama-3.1-405b": {
    "Together": "llama-3.1-405b",
    "Airforce": "llama-3.1-405b-instruct",
    "Puter": [
      "openrouter:meta-llama/llama-3.1-405b:free",
      "openrouter:meta-llama/llama-3.1-405b",
      "openrouter:meta-llama/llama-3.1-405b-instruct"
    ]
  },
  "llama-3.2-3b": {
    "Together": "llama-3.2-3b",
    "Cloudflare": "@cf/meta/llama-3.2-3b-instruct",
    "KiloCode": "meta-llama/llama-3.2-3b-instruct",
    "OpenRouter": "meta-llama/llama-3.2-3b-instruct",
    "Puter": [
      "openrouter:meta-llama/llama-3.2-3b-instruct:free",
      "openrouter:meta-llama/llama-3.2-3b-instruct"
    ]
  },
  "llama-3.2-90b": {
    "Together": "llama-3.2-90b",
    "Puter": "openrouter:meta-llama/llama-3.2-90b-vision-instruct"
  },
  "llama-4-scout": {
    "Pollinations": "llamascout",
    "Together": "llama-4-scout",
    "Cloudflare": "@cf/meta/llama-4-scout-17b-16e-instruct",
    "KiloCode": "meta-llama/llama-4-scout",
    "OpenRouter": "meta-llama/llama-4-scout",
    "Puter": [
      "openrouter:meta-llama/llama-4-scout:free",
      "openrouter:meta-llama/llama-4-scout"
    ]
  },
  "llama-4-maverick": {
    "Together": "llama-4-maverick",
    "RelayRouter": "llama-4-maverick",
    "KiloCode": "meta-llama/llama-4-maverick",
    "OpenRouter": "meta-llama/llama-4-maverick",
    "Puter": [
      "openrouter:meta-llama/llama-4-maverick:free",
      "openrouter:meta-llama/llama-4-maverick"
    ]
  },
  "mistral-7b": {
    "Together": "mistral-7b"
  },
  "mixtral-8x7b": {
    "Together": "mixtral-8x7b",
    "Groq": "mixtral-8x7b-32768"
  },
  "mistral-small-24b": {
    "Together": "mistral-small-24b"
  },
  "mistral-small-3.1-24b": {
    "Pollinations": "mistral-small",
    "Cloudflare": "@cf/mistralai/mistral-small-3.1-24b-instruct",
    "G4FSpace": "srv_mtkdrhxt45fe276b15c0:@cf/mistralai/mistral-small-3.1-24b-instruct",
    "KiloCode": "mistralai/mistral-small-3.1-24b-instruct",
    "OpenRouter": "mistralai/mistral-small-3.1-24b-instruct",
    "Puter": "openrouter:mistralai/mistral-small-3.1-24b-instruct"
  },
  "hermes-2-dpo": {
    "Together": "hermes-2-dpo",
    "Puter": "openrouter:nousresearch/nous-hermes-2-mixtral-8x7b-dpo"
  },
  "gemini-2.5-flash": {
    "Gemini": "gemini-2.5-flash",
    "GeminiPro": "gemini-2.5-flash",
    "GeminiCLI": "gemini-2.5-flash",
    "Airforce": "gemini-2.5-flash",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-2.5-flash",
    "LMArena": "gemini-2.5-flash",
    "KiloCode": "google/gemini-2.5-flash",
    "OpenRouter": "google/gemini-2.5-flash:batch",
    "Puter": "openrouter:google/gemini-2.5-flash-preview"
  },
  "gemini-2.5-pro": {
    "Gemini": "gemini-2.5-pro",
    "GeminiPro": "gemini-2.5-pro",
    "GeminiCLI": "gemini-2.5-pro",
    "Airforce": "gemini-2.5-pro",
    "LMArena": "gemini-2.5-pro",
    "KiloCode": "google/gemini-2.5-pro-preview",
    "OpenRouter": "google/gemini-2.5-pro-preview",
    "Puter": [
      "openrouter:google/gemini-2.5-pro-preview",
      "openrouter:google/gemini-2.5-pro-exp-03-25"
    ]
  },
  "gemini-3-pro-preview": {
    "GeminiCLI": "gemini-3-pro-preview",
    "GeminiPro": "gemini-3-pro-preview"
  },
  "gemini-3.1-pro": {
    "Gemini": "gemini-3.1-pro",
    "Airforce": "gemini-3.1-pro-preview",
    "GeminiPro": "gemini-3.1-pro",
    "LMArena": "gemini-3.1-pro-preview",
    "KiloCode": "google/gemini-3.1-pro-preview",
    "OpenCode": "gemini-3.1-pro",
    "OpenRouter": "google/gemini-3.1-pro-preview:batch",
    "Puter": "openrouter:google/gemini-3.1-pro-preview:batch"
  },
  "gemini-3.1-flash-lite": {
    "Gemini": "gemini-3.1-flash-lite",
    "Antigravity": "gemini-3.1-flash-lite",
    "Airforce": "gemini-3.1-flash-lite",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.1-flash-lite-preview",
    "GeminiPro": "gemini-3.1-flash-lite",
    "LMArena": "gemini-3.1-flash-lite",
    "KiloCode": "google/gemini-3.1-flash-lite-preview",
    "OpenRouter": "google/gemini-3.1-flash-lite-preview",
    "Puter": "openrouter:google/gemini-3.1-flash-lite:batch"
  },
  "gemini-3.6-flash": {
    "Gemini": "gemini-3.6-flash",
    "Antigravity": "gemini-3.6-flash",
    "Airforce": "gemini-3.6-flash",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.6-flash",
    "GeminiPro": "gemini-3.6-flash",
    "GithubCopilot": "gemini-3.6-flash",
    "LMArena": "gemini-3.6-flash",
    "KiloCode": "google/gemini-3.6-flash",
    "OpenCode": "gemini-3.6-flash",
    "OpenRouter": "google/gemini-3.6-flash:batch",
    "Puter": "openrouter:google/gemini-3.6-flash:batch"
  },
  "gemini-3.7-flash": {
    "Gemini": "gemini-3.7-flash",
    "Antigravity": "gemini-3.7-flash",
    "Airforce": "gemini-3.7-flash",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.7-flash",
    "GeminiPro": "gemini-3.7-flash",
    "GithubCopilot": "gemini-3.7-flash",
    "LMArena": "gemini-3.7-flash",
    "KiloCode": "google/gemini-3.7-flash",
    "OpenCode": "gemini-3.7-flash",
    "OpenRouter": "google/gemini-3.7-flash:batch",
    "Puter": "openrouter:google/gemini-3.7-flash:batch"
  },
  "gemini-3.8-flash": {
    "Gemini": "gemini-3.8-flash",
    "Antigravity": "gemini-3.8-flash",
    "Airforce": "gemini-3.8-flash",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.8-flash",
    "GeminiPro": "gemini-3.8-flash",
    "GithubCopilot": "gemini-3.8-flash",
    "KiloCode": "google/gemini-3.8-flash",
    "OpenCode": "gemini-3.8-flash",
    "OpenRouter": "google/gemini-3.8-flash:batch",
    "Puter": "openrouter:google/gemini-3.8-flash:batch"
  },
  "gemini-3.8-pro": {
    "Gemini": "gemini-3.8-pro",
    "GeminiPro": "gemini-3.8-pro"
  },
  "gemini-3.5-flash-lite": {
    "Gemini": "gemini-3.5-flash-lite",
    "Airforce": "gemini-3.5-flash-lite",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.5-flash-lite",
    "GeminiPro": "gemini-3.5-flash-lite",
    "LMArena": "gemini-3.5-flash-lite",
    "KiloCode": "google/gemini-3.5-flash-lite",
    "OpenCode": "gemini-3.5-flash-lite",
    "OpenRouter": "google/gemini-3.5-flash-lite:batch",
    "Puter": "openrouter:google/gemini-3.5-flash-lite:batch"
  },
  "gemini-3.5-flash": {
    "Gemini": "gemini-3.5-flash",
    "Airforce": "gemini-3.5-flash",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-3.5-flash",
    "GeminiPro": "gemini-3.5-flash",
    "GithubCopilot": "gemini-3.5-flash",
    "LMArena": "gemini-3.5-flash",
    "KiloCode": "google/gemini-3.5-flash",
    "OpenCode": "gemini-3.5-flash",
    "OpenRouter": "google/gemini-3.5-flash:batch",
    "Puter": "openrouter:google/gemini-3.5-flash:batch"
  },
  "gemini-3.5-flash-thinking": {
    "Gemini": "gemini-3.5-flash-thinking",
    "GeminiPro": "gemini-3.5-flash-thinking"
  },
  "gemini-auto": {
    "Gemini": "gemini-auto",
    "GeminiPro": "gemini-auto"
  },
  "gemini-3.5-flash-thinking-lite": {
    "Gemini": "gemini-3.5-flash-thinking-lite",
    "GeminiPro": "gemini-3.5-flash-thinking-lite"
  },
  "gemini-flash-lite": {
    "Gemini": "gemini-flash-lite",
    "Airforce": "gemini-flash-lite-latest",
    "G4FSpace": "srv_mrgy0nmbc8a86c407f17:models/gemini-flash-lite-latest",
    "GeminiPro": "gemini-flash-lite"
  },
  "command-r7b": {
    "HuggingSpace": [
      "command-r7b-12-2024",
      "command-r7b-arabic-02-2025"
    ],
    "CohereForAI_C4AI_Command": [
      "command-r7b-12-2024",
      "command-r7b-arabic-02-2025"
    ],
    "Puter": "openrouter:cohere/command-r7b-12-2024"
  },
  "command-a": {
    "HuggingSpace": "command-a-03-2025",
    "CohereForAI_C4AI_Command": "command-a-03-2025",
    "KiloCode": "cohere/command-a",
    "OpenRouter": "cohere/command-a",
    "Puter": "openrouter:cohere/command-a"
  },
  "qwen-2.5-coder-32b": {
    "Together": "qwen-2.5-coder-32b",
    "HuggingChat": "Qwen/Qwen2.5-Coder-32B-Instruct",
    "HuggingFace": "Qwen/Qwen2.5-Coder-32B-Instruct",
    "Cloudflare": "@cf/qwen/qwen2.5-coder-32b-instruct",
    "KiloCode": "qwen/qwen-2.5-coder-32b-instruct",
    "OpenRouter": "qwen/qwen-2.5-coder-32b-instruct",
    "Pollinations": "qwen-3-coder",
    "Puter": [
      "openrouter:qwen/qwen-2.5-coder-32b-instruct:free",
      "openrouter:qwen/qwen-2.5-coder-32b-instruct"
    ]
  },
  "qwen-2.5-vl-72b": {
    "Together": "qwen-2.5-vl-72b",
    "HuggingFace": "Qwen/Qwen2.5-VL-72B-Instruct",
    "HuggingChat": "Qwen/Qwen2.5-VL-72B-Instruct",
    "KiloCode": "qwen/qwen2.5-vl-72b-instruct",
    "OpenRouter": "qwen/qwen2.5-vl-72b-instruct",
    "Puter": [
      "openrouter:qwen/qwen2.5-vl-72b-instruct:free",
      "openrouter:qwen/qwen2.5-vl-72b-instruct"
    ]
  },
  "qwen-3-235b": {
    "Together": "qwen-3-235b",
    "Puter": [
      "openrouter:qwen/qwen3-235b-a22b:free",
      "openrouter:qwen/qwen3-235b-a22b"
    ]
  },
  "qwen-3-32b": {
    "Together": "qwen-3-32b",
    "HuggingFace": "Qwen/Qwen3-32B",
    "Airforce": "qwen3-32b",
    "HuggingChat": "Qwen/Qwen3-32B",
    "KiloCode": "qwen/qwen3-32b",
    "OpenRouter": "qwen/qwen3-32b",
    "Puter": [
      "openrouter:qwen/qwen3-32b:free",
      "openrouter:qwen/qwen3-32b"
    ]
  },
  "qwq-32b": {
    "Together": "qwq-32b",
    "HuggingChat": "qwq-32b",
    "Airforce": "qwq-32b-preview",
    "Cloudflare": "@cf/qwen/qwq-32b",
    "LMArena": "qwq-32b",
    "Puter": [
      "openrouter:qwen/qwq-32b-preview",
      "openrouter:qwen/qwq-32b:free",
      "openrouter:qwen/qwq-32b"
    ]
  },
  "deepseek-v3": {
    "Together": "deepseek-v3",
    "DeepSeek": "deepseek-chat",
    "Puter": "openrouter:deepseek/deepseek-v3-base:free"
  },
  "deepseek-r1": {
    "Pollinations": "deepseek-reasoning",
    "Together": "deepseek-r1",
    "HuggingFace": "deepseek-ai/DeepSeek-R1",
    "Airforce": "deepseek-r1",
    "Cerebras": "deepseek-r1-distill-llama-70b",
    "DeepSeek": "deepseek-r1",
    "HuggingChat": "deepseek-ai/DeepSeek-R1",
    "KiloCode": "deepseek/deepseek-r1",
    "OpenRouter": "deepseek/deepseek-r1",
    "Puter": [
      "deepseek-reasoner",
      "openrouter:deepseek/deepseek-r1:free",
      "openrouter:deepseek/deepseek-r1"
    ]
  },
  "deepseek-r1-distill-llama-70b": {
    "Together": "deepseek-r1-distill-llama-70b",
    "HuggingFace": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    "Cerebras": "deepseek-r1-distill-llama-70b",
    "HuggingChat": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    "KiloCode": "deepseek/deepseek-r1-distill-llama-70b",
    "OpenRouter": "deepseek/deepseek-r1-distill-llama-70b",
    "Puter": [
      "openrouter:deepseek/deepseek-r1-distill-llama-70b:free",
      "openrouter:deepseek/deepseek-r1-distill-llama-70b"
    ]
  },
  "deepseek-r1-distill-qwen-1.5b": {
    "Together": "deepseek-r1-distill-qwen-1.5b",
    "Puter": "openrouter:deepseek/deepseek-r1-distill-qwen-1.5b"
  },
  "deepseek-r1-distill-qwen-14b": {
    "Together": "deepseek-r1-distill-qwen-14b",
    "HuggingFace": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    "HuggingChat": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    "Puter": [
      "openrouter:deepseek/deepseek-r1-distill-qwen-14b:free",
      "openrouter:deepseek/deepseek-r1-distill-qwen-14b"
    ]
  },
  "grok-2": {
    "Grok": "auto",
    "Puter": [
      "openrouter:x-ai/grok-2-vision-1212",
      "openrouter:x-ai/grok-2-1212"
    ]
  },
  "grok-3": {
    "Grok": "auto",
    "Airforce": "grok-3"
  },
  "grok-3-r1": {
    "Grok": "reasoning"
  },
  "kimi-k2": {
    "Groq": "moonshotai/Kimi-K2-Instruct",
    "HuggingFace": "moonshotai/Kimi-K2-Instruct",
    "Airforce": "kimi-k2-instruct",
    "HuggingChat": "moonshotai/Kimi-K2-Instruct",
    "KiloCode": "moonshotai/kimi-k2",
    "OpenRouter": "moonshotai/kimi-k2",
    "Puter": "openrouter:moonshotai/kimi-k2"
  },
  "sonar": {
    "Puter": "openrouter:perplexity/sonar",
    "KiloCode": "perplexity/sonar",
    "OpenRouter": "perplexity/sonar"
  },
  "sonar-pro": {
    "Puter": "openrouter:perplexity/sonar-pro",
    "KiloCode": "perplexity/sonar-pro",
    "OpenRouter": "perplexity/sonar-pro"
  },
  "sonar-reasoning": {
    "Puter": "openrouter:perplexity/sonar-reasoning"
  },
  "sonar-reasoning-pro": {
    "Puter": "openrouter:perplexity/sonar-reasoning-pro",
    "KiloCode": "perplexity/sonar-reasoning-pro",
    "OpenRouter": "perplexity/sonar-reasoning-pro"
  },
  "r1-1776": {
    "Together": "r1-1776",
    "Puter": "openrouter:perplexity/r1-1776",
    "Perplexity": "r1-1776"
  },
  "nemotron-70b": {
    "Together": "nemotron-70b",
    "HuggingChat": "nemotron-70b",
    "Puter": "openrouter:nvidia/llama-3.1-nemotron-70b-instruct"
  },
  "aria": {
    "OperaAria": "aria"
  },
  "sdxl-turbo": {
    "HuggingFaceMedia": "stabilityai/sdxl-turbo",
    "PollinationsImage": "sdxl-turbo",
    "Pollinations": "turbo"
  },
  "sd-3.5-large": {
    "HuggingFaceMedia": "stabilityai/stable-diffusion-3.5-large",
    "HuggingSpace": "stabilityai-stable-diffusion-3-5-large",
    "StabilityAI_SD35Large": "stabilityai-stable-diffusion-3-5-large"
  },
  "flux": {
    "HuggingFaceMedia": "black-forest-labs/FLUX.1-dev",
    "PollinationsImage": "flux",
    "Together": "flux",
    "HuggingSpace": "black-forest-labs-flux-1-dev",
    "BlackForestLabs_Flux1Dev": "black-forest-labs-flux-1-dev",
    "Pollinations": "flux"
  },
  "flux-pro": {
    "PollinationsImage": "flux-pro",
    "Together": "flux-pro",
    "Pollinations": "flux"
  },
  "flux-kontext": {
    "Pollinations": "kontext",
    "Together": "flux-kontext"
  },
  "deepseek-v4.1-flash": {
    "DeepInfra": "deepseek-ai/DeepSeek-V4.1-Flash",
    "HuggingFace": "deepseek-ai/DeepSeek-V4.1-Flash",
    "Airforce": "deepseek-v4.1-flash",
    "HuggingChat": "deepseek-ai/DeepSeek-V4.1-Flash",
    "KiloCode": "deepseek/deepseek-v4.1-flash",
    "Ollama": "deepseek-v4.1-flash",
    "OpenCode": "deepseek-v4.1-flash",
    "OpenRouter": "deepseek/deepseek-v4.1-flash",
    "Puter": "togetherai:deepseek-ai/deepseek-v4.1-flash"
  },
  "glm-5.3": {
    "DeepInfra": "zai-org/GLM-5.3",
    "HuggingFace": "zai-org/GLM-5.3-BF16",
    "Airforce": "glm-5.3",
    "G4FSpace": "srv_mp2huzrg06e426ad12f3:zai-org/GLM-5.3",
    "GLM": "GLM-5.3",
    "HuggingChat": "zai-org/GLM-5.3-BF16",
    "Nvidia": "z-ai/glm-5.3",
    "KiloCode": "z-ai/glm-5.3",
    "Ollama": "glm-5.3",
    "OpenCode": "glm-5.3",
    "OpenRouter": "z-ai/glm-5.3:batch",
    "Puter": "z-ai:z-ai/glm-5.3"
  },
  "glm-5.3-flash": {
    "DeepInfra": "zai-org/GLM-5.3-Flash",
    "HuggingFace": "zai-org/GLM-5.3-Flash-BF16",
    "Airforce": "glm-5.3-flash",
    "G4FSpace": "srv_mkombumpae45db46dcb8:z-ai/glm-5.3-flash",
    "GLM": "GLM-5.3-Flash",
    "HuggingChat": "zai-org/GLM-5.3-Flash-BF16",
    "Nvidia": "z-ai/glm-5.3-flash",
    "KiloCode": "z-ai/glm-5.3-flash",
    "Ollama": "glm-5.3-flash",
    "OpenCode": "glm-5.3-flash",
    "OpenRouter": "z-ai/glm-5.3-flash:batch",
    "Puter": "z-ai:z-ai/glm-5.3-flash"
  },
  "kimi-k3": {
    "DeepInfra": "moonshotai/Kimi-K3",
    "HuggingFace": "moonshotai/Kimi-K3",
    "Airforce": "kimi-k3",
    "GithubCopilot": "kimi-k3",
    "HuggingChat": "moonshotai/Kimi-K3",
    "Nvidia": "moonshotai/kimi-k3",
    "KiloCode": "moonshotai/kimi-k3",
    "Ollama": "kimi-k3",
    "OpenCode": "kimi-k3",
    "OpenRouter": "moonshotai/kimi-k3:batch",
    "Puter": "togetherai:moonshotai/kimi-k3"
  },
  "qwen-3.8-2.4t-a95b": {
    "DeepInfra": "Qwen/Qwen3.8-2.4T-A95B",
    "HuggingFace": "Qwen/Qwen3.8-2.4T-A95B",
    "HuggingChat": "Qwen/Qwen3.8-2.4T-A95B",
    "KiloCode": "qwen/qwen3.8-2.4t-a95b",
    "OpenRouter": "qwen/qwen3.8-2.4t-a95b:batch",
    "Puter": "togetherai:qwen/qwen3.8-2.4t-a95b"
  },
  "deepseek-v4-pro-0813": {
    "DeepInfra": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "HuggingFace": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "Airforce": "deepseek-v4-pro-0813",
    "G4FSpace": "HuggingChat:deepseek-ai/DeepSeek-V4-Pro-0813",
    "HuggingChat": "deepseek-ai/DeepSeek-V4-Pro-0813",
    "KiloCode": "deepseek/deepseek-v4-pro-0813",
    "OpenRouter": "deepseek/deepseek-v4-pro-0813:batch",
    "Puter": "togetherai:deepseek-ai/deepseek-v4-pro-0813"
  },
  "deepseek-v4-flash-0731": {
    "DeepInfra": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "HuggingFace": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "G4FSpace": "srv_mkombumpae45db46dcb8:deepseek-ai/deepseek-v4-flash-0731",
    "HuggingChat": "deepseek-ai/DeepSeek-V4-Flash-0731",
    "Nvidia": "deepseek-ai/deepseek-v4-flash-0731",
    "KiloCode": "deepseek/deepseek-v4-flash-0731",
    "OpenRouter": "deepseek/deepseek-v4-flash-0731:batch",
    "Puter": "togetherai:deepseek-ai/deepseek-v4-flash-0731"
  },
  "glm-5.2": {
    "DeepInfra": "zai-org/GLM-5.2",
    "HuggingFace": "zai-org/GLM-5.2-FP8",
    "Airforce": "glm-5.2",
    "Cloudflare": "@cf/zai-org/glm-5.2",
    "G4FSpace": "srv_monk1pkz433a519ff2be:z-ai/glm-5.2:free",
    "GLM": "GLM-5.2",
    "HuggingChat": "zai-org/GLM-5.2-FP8",
    "KiloCode": "z-ai/glm-5.2:free",
    "Ollama": "glm-5.2",
    "OpenCode": "glm-5.2",
    "OpenRouter": "z-ai/glm-5.2:free",
    "OpenRouterFree": "z-ai/glm-5.2:free",
    "Puter": "z-ai:z-ai/glm-5.2"
  },
  "kimi-k2.7-code": {
    "DeepInfra": "moonshotai/Kimi-K2.7-Code",
    "HuggingFace": "moonshotai/Kimi-K2.7-Code",
    "Airforce": "kimi-k2.7-code",
    "Cloudflare": "@cf/moonshotai/kimi-k2.7-code",
    "GithubCopilot": "kimi-k2.7-code",
    "HuggingChat": "moonshotai/Kimi-K2.7-Code",
    "KiloCode": "moonshotai/kimi-k2.7-code",
    "Ollama": "kimi-k2.7-code",
    "OpenCode": "kimi-k2.7-code",
    "OpenRouter": "moonshotai/kimi-k2.7-code",
    "Puter": "openrouter:moonshotai/kimi-k2.7-code"
  },
  "nemotron-3-ultra-550b-a55b": {
    "DeepInfra": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
    "HuggingFace": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    "G4FSpace": "srv_mp5miql908c8738d71be:community/NamanSoni78/nemotron-3-ultra-550b-a55b",
    "HuggingChat": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
    "Nvidia": "nvidia/nemotron-3-ultra-550b-a55b",
    "KiloCode": "nvidia/nemotron-3-ultra-550b-a55b",
    "OpenRouter": "nvidia/nemotron-3-ultra-550b-a55b:free",
    "OpenRouterFree": "nvidia/nemotron-3-ultra-550b-a55b:free",
    "Pollinations": "community/NamanSoni78/nemotron-3-ultra-550b-a55b",
    "Puter": "openrouter:nvidia/nemotron-3-ultra-550b-a55b:free"
  },
  "deepseek-v4-flash": {
    "DeepInfra": "deepseek-ai/DeepSeek-V4-Flash",
    "HuggingFace": "deepseek-ai/DeepSeek-V4-Flash",
    "Airforce": "deepseek-v4-flash",
    "G4FSpace": "srv_mtsj8uzo97d3c0d49960:deepseek-z/deepseek-v4-flash",
    "HuggingChat": "deepseek-ai/DeepSeek-V4-Flash",
    "RelayRouter": "deepseek-v4-flash",
    "KiloCode": "deepseek/deepseek-v4-flash",
    "Ollama": "deepseek-v4-flash:0731",
    "OpenCode": "deepseek-v4-flash-free",
    "OpenRouter": "deepseek/deepseek-v4-flash",
    "OrcaRouter": "deepseek/deepseek-v4-flash-free",
    "Puter": "openrouter:~deepseek/deepseek-v4-flash-latest"
  },
  "deepseek-v4-pro": {
    "DeepInfra": "deepseek-ai/DeepSeek-V4-Pro",
    "HuggingFace": "deepseek-ai/DeepSeek-V4-Pro",
    "Airforce": "deepseek-v4-pro",
    "G4FSpace": "srv_mr9dda21bf67b4c62086:deepseek/deepseek-v4-pro",
    "HuggingChat": "deepseek-ai/DeepSeek-V4-Pro",
    "KiloCode": "deepseek/deepseek-v4-pro",
    "Ollama": "deepseek-v4-pro:0813",
    "OpenCode": "deepseek-v4-pro",
    "OpenRouter": "deepseek/deepseek-v4-pro",
    "Puter": "openrouter:deepseek/deepseek-v4-pro"
  },
  "kimi-k2.6": {
    "DeepInfra": "moonshotai/Kimi-K2.6",
    "HuggingFace": "moonshotai/Kimi-K2.6",
    "Airforce": "kimi-k2.6",
    "Cloudflare": "@cf/moonshotai/kimi-k2.6",
    "HuggingChat": "moonshotai/Kimi-K2.6",
    "Nvidia": "moonshotai/kimi-k2.6",
    "KiloCode": "moonshotai/kimi-k2.6",
    "Ollama": "kimi-k2.6",
    "OpenCode": "kimi-k2.6",
    "OpenRouter": "moonshotai/kimi-k2.6",
    "Puter": "openrouter:moonshotai/kimi-k2.6"
  },
  "mimo-v2.5-pro": {
    "DeepInfra": "XiaomiMiMo/MiMo-V2.5-Pro",
    "HuggingFace": "XiaomiMiMo/MiMo-V2.5-Pro",
    "Airforce": "mimo-v2.5-pro",
    "G4FSpace": "HuggingChat:XiaomiMiMo/MiMo-V2.5-Pro",
    "HuggingChat": "XiaomiMiMo/MiMo-V2.5-Pro",
    "LMArena": "mimo-v2.5-pro",
    "KiloCode": "xiaomi/mimo-v2.5-pro",
    "OpenRouter": "xiaomi/mimo-v2.5-pro",
    "Puter": "openrouter:xiaomi/mimo-v2.5-pro"
  },
  "qwen-3.6-35b-a3b": {
    "DeepInfra": "Qwen/Qwen3.6-35B-A3B",
    "HuggingFace": "Qwen/Qwen3.6-35B-A3B",
    "Airforce": "qwen3.6-35b-a3b",
    "HuggingChat": "Qwen/Qwen3.6-35B-A3B",
    "KiloCode": "qwen/qwen3.6-35b-a3b",
    "OpenRouter": "qwen/qwen3.6-35b-a3b",
    "Puter": "openrouter:qwen/qwen3.6-35b-a3b",
    "Qwen": "qwen3.6-35b-a3b"
  },
  "glm-5.1": {
    "DeepInfra": "zai-org/GLM-5.1",
    "HuggingFace": "zai-org/GLM-5.1",
    "Airforce": "glm-5.1",
    "HuggingChat": "zai-org/GLM-5.1",
    "LMArena": "glm-5.1",
    "KiloCode": "z-ai/glm-5.1",
    "Ollama": "glm-5.1",
    "OpenCode": "glm-5.1",
    "OpenRouter": "z-ai/glm-5.1",
    "Puter": "z-ai:z-ai/glm-5.1"
  },
  "qwen-3.5-397b-a17b": {
    "DeepInfra": "Qwen/Qwen3.5-397B-A17B",
    "HuggingFace": "Qwen/Qwen3.5-397B-A17B",
    "Airforce": "qwen3.5-397b-a17b",
    "HuggingChat": "Qwen/Qwen3.5-397B-A17B",
    "LMArena": "qwen3.5-397b-a17b",
    "KiloCode": "qwen/qwen3.5-397b-a17b",
    "OpenRouter": "qwen/qwen3.5-397b-a17b",
    "Puter": "openrouter:qwen/qwen3.5-397b-a17b",
    "Qwen": "qwen3.5-397b-a17b"
  },
  "gemma-4-26b-a4b-it": {
    "DeepInfra": "google/gemma-4-26B-A4B-it",
    "HuggingFace": "google/gemma-4-26B-A4B-it",
    "Cloudflare": "@cf/google/gemma-4-26b-a4b-it",
    "GeminiPro": "gemma-4-26b-a4b-it",
    "HuggingChat": "google/gemma-4-26B-A4B-it",
    "KiloCode": "google/gemma-4-26b-a4b-it",
    "OpenRouter": "google/gemma-4-26b-a4b-it:free",
    "OpenRouterFree": "google/gemma-4-26b-a4b-it:free",
    "Puter": "openrouter:google/gemma-4-26b-a4b-it:free"
  },
  "gemma-4-31b-it": {
    "DeepInfra": "google/gemma-4-31B-it",
    "HuggingFace": "google/gemma-4-31B-it",
    "GeminiPro": "gemma-4-31b-it",
    "HuggingChat": "google/gemma-4-31B-it",
    "Nvidia": "google/gemma-4-31b-it",
    "KiloCode": "google/gemma-4-31b-it",
    "OpenRouter": "google/gemma-4-31b-it:free",
    "OpenRouterFree": "google/gemma-4-31b-it:free",
    "Puter": "openrouter:google/gemma-4-31b-it:free"
  },
  "nemotron-3-super-120b-a12b": {
    "DeepInfra": "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
    "G4FSpace": "srv_mkombumpae45db46dcb8:nvidia/nemotron-3-super-120b-a12b",
    "Nvidia": "nvidia/nemotron-3-super-120b-a12b",
    "KiloCode": "nvidia/nemotron-3-super-120b-a12b:free",
    "OpenRouter": "nvidia/nemotron-3-super-120b-a12b:free",
    "OpenRouterFree": "nvidia/nemotron-3-super-120b-a12b:free",
    "Puter": "openrouter:nvidia/nemotron-3-super-120b-a12b:free"
  },
  "qwen-3-max": {
    "DeepInfra": "Qwen/Qwen3-Max",
    "Airforce": "qwen3-max-preview",
    "LMArena": "qwen3-max-2025-09-26",
    "KiloCode": "qwen/qwen3-max",
    "OpenRouter": "qwen/qwen3-max",
    "Puter": "openrouter:qwen/qwen3-max",
    "Qwen": "qwen3-max-2026-01-23"
  },
  "qwen-3-max-thinking": {
    "DeepInfra": "Qwen/Qwen3-Max-Thinking",
    "LMArena": "qwen3-max-thinking",
    "KiloCode": "qwen/qwen3-max-thinking",
    "OpenRouter": "qwen/qwen3-max-thinking",
    "Puter": "openrouter:qwen/qwen3-max-thinking"
  },
  "deepseek-v3.2": {
    "DeepInfra": "deepseek-ai/DeepSeek-V3.2",
    "HuggingFace": "deepseek-ai/DeepSeek-V3.2",
    "Airforce": "deepseek-v3.2",
    "HuggingChat": "deepseek-ai/DeepSeek-V3.2",
    "KiloCode": "deepseek/deepseek-v3.2",
    "OpenRouter": "deepseek/deepseek-v3.2",
    "Puter": "openrouter:deepseek/deepseek-v3.2"
  },
  "flux-2-klein-4b": {
    "DeepInfra": "black-forest-labs/FLUX-2-klein-4b"
  },
  "flux-2-klein-9b": {
    "DeepInfra": "black-forest-labs/FLUX-2-klein-9b"
  },
  "qwen-3.8-27b": {
    "HuggingFace": "Qwen/Qwen3.8-27B",
    "Airforce": "qwen3.8-27b",
    "G4FSpace": "srv_mtsj8uzo97d3c0d49960:openrouter-z/qwen3.8-27b",
    "Groq": "qwen/qwen3.8-27b",
    "HuggingChat": "Qwen/Qwen3.8-27B",
    "KiloCode": "qwen/qwen3.8-27b:free",
    "OpenRouter": "qwen/qwen3.8-27b:free",
    "OpenRouterFree": "qwen/qwen3.8-27b:free",
    "OrcaRouter": "qwen/qwen3.8-27b-free",
    "Puter": "openrouter:qwen/qwen3.8-27b:free"
  },
  "qwen-3-8b": {
    "HuggingFace": "Qwen/Qwen3-8B",
    "Airforce": "qwen3-8b",
    "HuggingChat": "Qwen/Qwen3-8B",
    "KiloCode": "qwen/qwen3-8b",
    "OpenRouter": "qwen/qwen3-8b",
    "Puter": [
      "openrouter:qwen/qwen3-8b:free",
      "openrouter:qwen/qwen3-8b"
    ]
  },
  "ternary-bonsai-27b-gguf": {
    "HuggingFace": "prism-ml/Ternary-Bonsai-27B-gguf",
    "HuggingChat": "prism-ml/Ternary-Bonsai-27B-gguf"
  },
  "deepseek-v4-flash-vision-exp": {
    "HuggingFace": "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
    "G4FSpace": "srv_mr9dda21bf67b4c62086:deepseek/deepseek-v4-flash-vision-exp",
    "HuggingChat": "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
    "KiloCode": "deepseek/deepseek-v4-flash-vision-exp",
    "OpenCode": "deepseek-v4-flash-vision-exp",
    "OpenRouter": "deepseek/deepseek-v4-flash-vision-exp:batch",
    "Puter": "openrouter:deepseek/deepseek-v4-flash-vision-exp:batch"
  },
  "qwen-3.5-9b": {
    "HuggingFace": "Qwen/Qwen3.5-9B",
    "G4FSpace": "HuggingChat:Qwen/Qwen3.5-9B",
    "HuggingChat": "Qwen/Qwen3.5-9B",
    "KiloCode": "qwen/qwen3.5-9b",
    "OpenRouter": "qwen/qwen3.5-9b:batch",
    "Puter": "togetherai:qwen/qwen3.5-9b"
  },
  "muse-glimmer-30b": {
    "HuggingFace": "meta-models/Muse-Glimmer-30B",
    "G4FSpace": "srv_mp5miql908c8738d71be:community/YoannDev90/muse-glimmer-30b:free",
    "HuggingChat": "meta-models/Muse-Glimmer-30B",
    "Nvidia": "meta/muse-glimmer-30b",
    "KiloCode": "meta/muse-glimmer-30b",
    "OpenRouter": "meta/muse-glimmer-30b:batch",
    "Pollinations": "community/YoannDev90/muse-glimmer-30b:free",
    "Puter": "togetherai:meta-models/muse-glimmer-30b"
  },
  "gpt-oss-20b": {
    "HuggingFace": "openai/gpt-oss-20b",
    "Airforce": "gpt-oss-20b",
    "Cloudflare": "@cf/openai/gpt-oss-20b",
    "G4FSpace": "srv_mkombumpae45db46dcb8:openai/gpt-oss-20b",
    "Groq": "openai/gpt-oss-20b",
    "HuggingChat": "openai/gpt-oss-20b",
    "LMArena": "gpt-oss-20b",
    "Nvidia": "openai/gpt-oss-20b",
    "KiloCode": "openai/gpt-oss-20b",
    "Ollama": "gpt-oss:20b",
    "OpenRouter": "openai/gpt-oss-20b",
    "Puter": "openrouter:openai/gpt-oss-20b"
  },
  "ling-3.0-flash-vl": {
    "HuggingFace": "inclusionAI/Ling-3.0-flash-VL",
    "G4FSpace": "srv_monk1pkz433a519ff2be:inclusionai/ling-3.0-flash-vl:free",
    "HuggingChat": "inclusionAI/Ling-3.0-flash-VL",
    "KiloCode": "inclusionai/ling-3.0-flash-vl",
    "OpenRouter": "inclusionai/ling-3.0-flash-vl:free",
    "OpenRouterFree": "inclusionai/ling-3.0-flash-vl:free",
    "Puter": "openrouter:inclusionai/ling-3.0-flash-vl:free"
  },
  "ling-3.0-flash-fin": {
    "HuggingFace": "inclusionAI/Ling-3.0-flash-Fin",
    "HuggingChat": "inclusionAI/Ling-3.0-flash-Fin",
    "KiloCode": "inclusionai/ling-3.0-flash-fin:free",
    "OpenCode": "ling-3.0-flash-fin-free",
    "OpenRouter": "inclusionai/ling-3.0-flash-fin:free",
    "OpenRouterFree": "inclusionai/ling-3.0-flash-fin:free",
    "Puter": "openrouter:inclusionai/ling-3.0-flash-fin:free"
  },
  "minimax-m3": {
    "HuggingFace": "MiniMaxAI/MiniMax-M3",
    "Airforce": "minimax-m3",
    "G4FSpace": "srv_mtsj8uzo97d3c0d49960:minimax-z/minimax-m3",
    "HuggingChat": "MiniMaxAI/MiniMax-M3",
    "LMArena": "minimax-m3",
    "MiniMax": "MiniMax-M3",
    "KiloCode": "minimax/minimax-m3",
    "Ollama": "minimax-m3",
    "OpenCode": "minimax-m3",
    "OpenRouter": "minimax/minimax-m3:batch",
    "Puter": "togetherai:minimaxai/minimax-m3"
  },
  "qwen-3-coder-next": {
    "HuggingFace": "Qwen/Qwen3-Coder-Next",
    "HuggingChat": "Qwen/Qwen3-Coder-Next",
    "KiloCode": "qwen/qwen3-coder-next",
    "OpenRouter": "qwen/qwen3-coder-next",
    "Puter": "openrouter:qwen/qwen3-coder-next"
  },
  "llama-3.3-70b": {
    "HuggingFace": "meta-llama/Llama-3.3-70B-Instruct",
    "Airforce": "llama-3.3-70b",
    "Cerebras": "llama-3.3-70b",
    "Cloudflare": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    "HuggingChat": "meta-llama/Llama-3.3-70B-Instruct",
    "KiloCode": "meta-llama/llama-3.3-70b-instruct",
    "OpenRouter": "meta-llama/llama-3.3-70b-instruct",
    "Puter": [
      "openrouter:meta-llama/llama-3.3-70b-instruct:free",
      "openrouter:meta-llama/llama-3.3-70b-instruct"
    ]
  },
  "qwen-3.6-27b": {
    "HuggingFace": "Qwen/Qwen3.6-27B",
    "HuggingChat": "Qwen/Qwen3.6-27B",
    "LMArena": "qwen3.6-27b",
    "KiloCode": "qwen/qwen3.6-27b",
    "OpenRouter": "qwen/qwen3.6-27b",
    "Puter": "openrouter:qwen/qwen3.6-27b",
    "Qwen": "qwen3.6-27b"
  },
  "apertus-v1.5-8b": {
    "HuggingFace": "swiss-ai/Apertus-v1.5-8B",
    "HuggingChat": "swiss-ai/Apertus-v1.5-8B"
  },
  "qwen-3-coder-30b-a3b": {
    "HuggingFace": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "Airforce": "qwen3-coder-30b-a3b",
    "HuggingChat": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "KiloCode": "qwen/qwen3-coder-30b-a3b-instruct",
    "OpenRouter": "qwen/qwen3-coder-30b-a3b-instruct",
    "Puter": "openrouter:qwen/qwen3-coder-30b-a3b-instruct"
  },
  "nemotron-3.5-lightning-30b-a3b": {
    "HuggingFace": "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
    "G4FSpace": "srv_mkombumpae45db46dcb8:nvidia/nemotron-3.5-lightning-30b-a3b",
    "HuggingChat": "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
    "Nvidia": "nvidia/nemotron-3.5-lightning-30b-a3b"
  },
  "ling-3.0-flash": {
    "HuggingFace": "inclusionAI/Ling-3.0-flash",
    "HuggingChat": "inclusionAI/Ling-3.0-flash",
    "KiloCode": "inclusionai/ling-3.0-flash",
    "OpenRouter": "inclusionai/ling-3.0-flash",
    "Puter": "openrouter:inclusionai/ling-3.0-flash"
  },
  "gemma-3-12b-it": {
    "HuggingFace": "google/gemma-3-12b-it",
    "GeminiPro": "gemma-3-12b-it",
    "HuggingChat": "google/gemma-3-12b-it",
    "Nvidia": "google/gemma-3-12b-it",
    "KiloCode": "google/gemma-3-12b-it",
    "OpenRouter": "google/gemma-3-12b-it",
    "Puter": "openrouter:google/gemma-3-12b-it"
  },
  "qwen-3.5-35b-a3b": {
    "HuggingFace": "Qwen/Qwen3.5-35B-A3B",
    "HuggingChat": "Qwen/Qwen3.5-35B-A3B",
    "LMArena": "qwen3.5-35b-a3b",
    "KiloCode": "qwen/qwen3.5-35b-a3b",
    "OpenRouter": "qwen/qwen3.5-35b-a3b",
    "Puter": "openrouter:qwen/qwen3.5-35b-a3b",
    "Qwen": "qwen3.5-35b-a3b"
  },
  "granite-4.2-3b": {
    "HuggingFace": "ibm-granite/granite-4.2-3b",
    "HuggingChat": "ibm-granite/granite-4.2-3b"
  },
  "ternary-bonsai-27b-awq-4bit": {
    "HuggingFace": "prism-ml/Ternary-Bonsai-27B-AWQ-4bit",
    "HuggingChat": "prism-ml/Ternary-Bonsai-27B-AWQ-4bit"
  },
  "granite-4.2-8b": {
    "HuggingFace": "ibm-granite/granite-4.2-8b",
    "HuggingChat": "ibm-granite/granite-4.2-8b",
    "KiloCode": "ibm-granite/granite-4.2-8b",
    "OpenRouter": "ibm-granite/granite-4.2-8b",
    "Puter": "openrouter:ibm-granite/granite-4.2-8b"
  },
  "qwen-3-4b-2507": {
    "HuggingFace": "Qwen/Qwen3-4B-Instruct-2507",
    "HuggingChat": "Qwen/Qwen3-4B-Instruct-2507"
  },
  "inkling": {
    "HuggingFace": "thinkingmachines/Inkling",
    "Airforce": "inkling",
    "HuggingChat": "thinkingmachines/Inkling",
    "KiloCode": "thinkingmachines/inkling",
    "OpenRouter": "thinkingmachines/inkling:free",
    "OpenRouterFree": "thinkingmachines/inkling:free",
    "Puter": "togetherai:thinkingmachines/inkling"
  },
  "gemma-3-4b-it": {
    "HuggingFace": "google/gemma-3-4b-it",
    "GeminiPro": "gemma-3-4b-it",
    "HuggingChat": "google/gemma-3-4b-it",
    "Nvidia": "google/gemma-3-4b-it",
    "KiloCode": "google/gemma-3-4b-it",
    "OpenRouter": "google/gemma-3-4b-it",
    "Puter": "openrouter:google/gemma-3-4b-it"
  },
  "phi-4": {
    "HuggingFace": "microsoft/phi-4",
    "HuggingChat": "microsoft/phi-4",
    "KiloCode": "microsoft/phi-4",
    "OpenRouter": "microsoft/phi-4",
    "Puter": "openrouter:microsoft/phi-4"
  },
  "glm-4.7-flash": {
    "HuggingFace": "zai-org/GLM-4.7-Flash",
    "Airforce": "glm-4.7-flash",
    "Cloudflare": "@cf/zai-org/glm-4.7-flash",
    "G4FSpace": "srv_mtkdrhxt45fe276b15c0:@cf/zai-org/glm-4.7-flash",
    "HuggingChat": "zai-org/GLM-4.7-Flash",
    "KiloCode": "z-ai/glm-4.7-flash",
    "OpenRouter": "z-ai/glm-4.7-flash",
    "Puter": "openrouter:z-ai/glm-4.7-flash"
  },
  "apertus-v1.5-70b": {
    "HuggingFace": "swiss-ai/Apertus-v1.5-70B",
    "HuggingChat": "swiss-ai/Apertus-v1.5-70B"
  },
  "qwen-3-14b": {
    "HuggingFace": "Qwen/Qwen3-14B",
    "Airforce": "qwen3-14b",
    "HuggingChat": "Qwen/Qwen3-14B",
    "KiloCode": "qwen/qwen3-14b",
    "OpenRouter": "qwen/qwen3-14b",
    "Puter": [
      "openrouter:qwen/qwen3-14b:free",
      "openrouter:qwen/qwen3-14b"
    ]
  },
  "bielik-11b-v3.0": {
    "HuggingFace": "speakleash/Bielik-11B-v3.0-Instruct",
    "HuggingChat": "speakleash/Bielik-11B-v3.0-Instruct"
  },
  "gemma-3-27b-it": {
    "HuggingFace": "google/gemma-3-27b-it",
    "GeminiPro": "gemma-3-27b-it",
    "HuggingChat": "google/gemma-3-27b-it",
    "LMArena": "gemma-3-27b-it",
    "KiloCode": "google/gemma-3-27b-it",
    "OpenRouter": "google/gemma-3-27b-it",
    "Puter": "openrouter:google/gemma-3-27b-it"
  },
  "llama-4-scout-17b-16e": {
    "HuggingFace": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "HuggingChat": "meta-llama/Llama-4-Scout-17B-16E-Instruct"
  },
  "inkling-small": {
    "HuggingFace": "thinkingmachines/Inkling-Small",
    "HuggingChat": "thinkingmachines/Inkling-Small",
    "LMArena": "inkling-small",
    "KiloCode": "thinkingmachines/inkling-small:free",
    "OpenRouter": "thinkingmachines/inkling-small:free",
    "OpenRouterFree": "thinkingmachines/inkling-small:free",
    "Puter": "openrouter:thinkingmachines/inkling-small:free"
  },
  "gpt-oss-safeguard-20b": {
    "HuggingFace": "openai/gpt-oss-safeguard-20b",
    "G4FSpace": "srv_mkom688d57c76d8a3542:openai/gpt-oss-safeguard-20b",
    "Groq": "openai/gpt-oss-safeguard-20b",
    "HuggingChat": "openai/gpt-oss-safeguard-20b",
    "KiloCode": "openai/gpt-oss-safeguard-20b",
    "OpenRouter": "openai/gpt-oss-safeguard-20b",
    "Puter": "openrouter:openai/gpt-oss-safeguard-20b"
  },
  "llama-guard-4-12b": {
    "HuggingFace": "meta-llama/Llama-Guard-4-12B",
    "HuggingChat": "meta-llama/Llama-Guard-4-12B",
    "Nvidia": "meta/llama-guard-4-12b",
    "KiloCode": "meta-llama/llama-guard-4-12b",
    "OpenRouter": "meta-llama/llama-guard-4-12b",
    "Puter": "openrouter:meta-llama/llama-guard-4-12b"
  },
  "l3-8b-stheno-v3.2": {
    "HuggingFace": "Sao10K/L3-8B-Stheno-v3.2",
    "HuggingChat": "Sao10K/L3-8B-Stheno-v3.2"
  },
  "kimi-k2.5": {
    "HuggingFace": "moonshotai/Kimi-K2.5",
    "Airforce": "kimi-k2.5",
    "HuggingChat": "moonshotai/Kimi-K2.5",
    "KiloCode": "moonshotai/kimi-k2.5",
    "OpenCode": "kimi-k2.5",
    "OpenRouter": "moonshotai/kimi-k2.5",
    "Puter": "openrouter:moonshotai/kimi-k2.5"
  },
  "qwen-3-30b-a3b": {
    "HuggingFace": "Qwen/Qwen3-30B-A3B",
    "Airforce": "qwen3-30b-a3b",
    "Cloudflare": "qwen3-30b-a3b",
    "HuggingChat": "Qwen/Qwen3-30B-A3B",
    "LMArena": "qwen3-30b-a3b",
    "KiloCode": "qwen/qwen3-30b-a3b",
    "OpenRouter": "qwen/qwen3-30b-a3b",
    "Puter": "openrouter:qwen/qwen3-30b-a3b"
  },
  "mimo-v2.5": {
    "HuggingFace": "XiaomiMiMo/MiMo-V2.5",
    "Airforce": "mimo-v2.5",
    "HuggingChat": "XiaomiMiMo/MiMo-V2.5",
    "LMArena": "mimo-v2.5",
    "RelayRouter": "mimo-v2.5",
    "KiloCode": "xiaomi/mimo-v2.5",
    "OpenCode": "mimo-v2.5-free",
    "OpenRouter": "xiaomi/mimo-v2.5",
    "Puter": "openrouter:xiaomi/mimo-v2.5"
  },
  "granite-4.2-30b": {
    "HuggingFace": "ibm-granite/granite-4.2-30b",
    "HuggingChat": "ibm-granite/granite-4.2-30b"
  },
  "qwen-2.5-coder-7b": {
    "HuggingFace": "Qwen/Qwen2.5-Coder-7B-Instruct",
    "HuggingChat": "Qwen/Qwen2.5-Coder-7B-Instruct",
    "Puter": "openrouter:qwen/qwen2.5-coder-7b-instruct"
  },
  "nemotron-3-ultra-550b-a55b-nvfp4": {
    "HuggingFace": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4",
    "HuggingChat": "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4"
  },
  "qwen-3.5-122b-a10b": {
    "HuggingFace": "Qwen/Qwen3.5-122B-A10B",
    "Airforce": "qwen3.5-122b-a10b",
    "HuggingChat": "Qwen/Qwen3.5-122B-A10B",
    "LMArena": "qwen3.5-122b-a10b",
    "KiloCode": "qwen/qwen3.5-122b-a10b",
    "OpenRouter": "qwen/qwen3.5-122b-a10b",
    "Puter": "openrouter:qwen/qwen3.5-122b-a10b",
    "Qwen": "qwen3.5-122b-a10b"
  },
  "llama-4-maverick-17b-128e": {
    "HuggingFace": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    "HuggingChat": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"
  },
  "step-3.7-flash": {
    "HuggingFace": "stepfun-ai/Step-3.7-Flash",
    "Airforce": "step-3.7-flash",
    "HuggingChat": "stepfun-ai/Step-3.7-Flash",
    "KiloCode": "stepfun/step-3.7-flash:free",
    "OpenRouter": "stepfun/step-3.7-flash",
    "Puter": "openrouter:stepfun/step-3.7-flash"
  },
  "qwen-3-vl-235b-a22b": {
    "HuggingFace": "Qwen/Qwen3-VL-235B-A22B-Instruct",
    "Airforce": "qwen3-vl-235b-a22b",
    "HuggingChat": "Qwen/Qwen3-VL-235B-A22B-Instruct",
    "LMArena": "qwen3-vl-235b-a22b-instruct",
    "KiloCode": "qwen/qwen3-vl-235b-a22b-instruct",
    "OpenRouter": "qwen/qwen3-vl-235b-a22b-instruct",
    "Puter": "openrouter:qwen/qwen3-vl-235b-a22b-instruct"
  },
  "qwen-3.5-27b": {
    "HuggingFace": "Qwen/Qwen3.5-27B",
    "HuggingChat": "Qwen/Qwen3.5-27B",
    "LMArena": "qwen3.5-27b",
    "KiloCode": "qwen/qwen3.5-27b",
    "OpenRouter": "qwen/qwen3.5-27b",
    "Puter": "openrouter:qwen/qwen3.5-27b",
    "Qwen": "qwen3.5-27b"
  },
  "qwen-3-235b-a22b-2507": {
    "HuggingFace": "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "Airforce": "qwen3-235b-a22b-instruct-2507",
    "HuggingChat": "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "LMArena": "qwen3-235b-a22b-instruct-2507",
    "KiloCode": "qwen/qwen3-235b-a22b-2507",
    "OpenRouter": "qwen/qwen3-235b-a22b-2507",
    "Puter": "openrouter:qwen/qwen3-235b-a22b-2507"
  },
  "deepseek-r1-0528": {
    "HuggingFace": "deepseek-ai/DeepSeek-R1-0528",
    "Airforce": "deepseek-r1-0528",
    "HuggingChat": "deepseek-ai/DeepSeek-R1-0528",
    "KiloCode": "deepseek/deepseek-r1-0528",
    "OpenRouter": "deepseek/deepseek-r1-0528",
    "Puter": "openrouter:deepseek/deepseek-r1-0528"
  },
  "glm-4.5-air": {
    "HuggingFace": "zai-org/GLM-4.5-Air",
    "Airforce": "glm-4.5-air",
    "GLM": "GLM-4.5-Air",
    "HuggingChat": "zai-org/GLM-4.5-Air",
    "KiloCode": "z-ai/glm-4.5-air",
    "OpenRouter": "z-ai/glm-4.5-air",
    "Puter": "z-ai:z-ai/glm-4.5-air"
  },
  "deepseek-v3-0324": {
    "HuggingFace": "deepseek-ai/DeepSeek-V3-0324",
    "HuggingChat": "deepseek-ai/DeepSeek-V3-0324",
    "Puter": [
      "deepseek-chat",
      "openrouter:deepseek/deepseek-chat-v3-0324:free",
      "openrouter:deepseek/deepseek-chat-v3-0324"
    ]
  },
  "minimax-m2.7": {
    "HuggingFace": "MiniMaxAI/MiniMax-M2.7",
    "Airforce": "minimax-m2.7",
    "HuggingChat": "MiniMaxAI/MiniMax-M2.7",
    "MiniMax": "MiniMax-M2.7",
    "KiloCode": "minimax/minimax-m2.7",
    "Ollama": "minimax-m2.7",
    "OpenCode": "minimax-m2.7",
    "OpenRouter": "minimax/minimax-m2.7",
    "Puter": "openrouter:minimax/minimax-m2.7"
  },
  "step-3.5-flash": {
    "HuggingFace": "stepfun-ai/Step-3.5-Flash",
    "Airforce": "step-3.5-flash",
    "HuggingChat": "stepfun-ai/Step-3.5-Flash",
    "LMArena": "step-3.5-flash",
    "KiloCode": "stepfun/step-3.5-flash",
    "OpenRouter": "stepfun/step-3.5-flash",
    "Puter": "openrouter:stepfun/step-3.5-flash"
  },
  "deepseek": {
    "HuggingFace": "deepseek-ai/DeepSeek-V3",
    "Airforce": "deepseek-v3",
    "HuggingChat": "deepseek-ai/DeepSeek-V3",
    "PhindAi": "deepseek"
  },
  "qwen-2.5-coder-3b": {
    "HuggingFace": "Qwen/Qwen2.5-Coder-3B-Instruct",
    "HuggingChat": "Qwen/Qwen2.5-Coder-3B-Instruct"
  },
  "autoglm-phone-9b-multilingual": {
    "HuggingFace": "zai-org/AutoGLM-Phone-9B-Multilingual",
    "HuggingChat": "zai-org/AutoGLM-Phone-9B-Multilingual"
  },
  "wizardlm-2-8x22b": {
    "HuggingFace": "alpindale/WizardLM-2-8x22B",
    "HuggingChat": "alpindale/WizardLM-2-8x22B",
    "KiloCode": "microsoft/wizardlm-2-8x22b",
    "OpenRouter": "microsoft/wizardlm-2-8x22b",
    "Puter": "openrouter:microsoft/wizardlm-2-8x22b"
  },
  "qwen-2.5-72b": {
    "HuggingFace": "Qwen/Qwen2.5-72B-Instruct",
    "KiloCode": "qwen/qwen-2.5-72b-instruct",
    "OpenRouter": "qwen/qwen-2.5-72b-instruct",
    "Puter": [
      "openrouter:qwen/qwen-2.5-72b-instruct:free",
      "openrouter:qwen/qwen-2.5-72b-instruct"
    ]
  },
  "deepseek-r1-distill-llama-8b": {
    "HuggingFace": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
    "HuggingChat": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
    "Puter": "openrouter:deepseek/deepseek-r1-distill-llama-8b"
  },
  "l3-8b-lunaris": {
    "HuggingFace": "Sao10K/L3-8B-Lunaris-v1",
    "HuggingChat": "Sao10K/L3-8B-Lunaris-v1"
  },
  "hy3": {
    "HuggingFace": "tencent/Hy3",
    "HuggingChat": "tencent/Hy3",
    "KiloCode": "tencent/hy3-preview",
    "OpenRouter": "tencent/hy3-preview",
    "OrcaRouter": "tencent/hy3-free",
    "Puter": "openrouter:tencent/hy3-preview"
  },
  "deepseek-r1-distill-qwen-7b": {
    "HuggingFace": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    "HuggingChat": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
  },
  "qwen-3-235b-a22b": {
    "HuggingFace": "Qwen/Qwen3-235B-A22B",
    "Airforce": "qwen3-235b-a22b",
    "HuggingChat": "Qwen/Qwen3-235B-A22B",
    "LMArena": "qwen3-235b-a22b",
    "KiloCode": "qwen/qwen3-235b-a22b",
    "OpenRouter": "qwen/qwen3-235b-a22b",
    "Puter": "openrouter:qwen/qwen3-235b-a22b"
  },
  "command-r24": {
    "HuggingFace": "CohereLabs/c4ai-command-r-08-2024",
    "HuggingSpace": "command-r-08-2024",
    "CohereForAI_C4AI_Command": "command-r-08-2024",
    "HuggingChat": "CohereLabs/c4ai-command-r-08-2024",
    "KiloCode": "cohere/command-r-08-2024",
    "OpenRouter": "cohere/command-r-08-2024",
    "Puter": "openrouter:cohere/command-r-08-2024"
  },
  "qwen-3-coder-480b-a35b": {
    "HuggingFace": "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    "Airforce": "qwen3-coder-480b-a35b",
    "HuggingChat": "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    "LMArena": "qwen3-coder-480b-a35b-instruct",
    "Puter": "infron:qwen/qwen3-coder-480b-a35b:priority"
  },
  "aya-expanse-32b": {
    "HuggingFace": "CohereLabs/aya-expanse-32b",
    "HuggingChat": "CohereLabs/aya-expanse-32b"
  },
  "kimi-k2-0905": {
    "HuggingFace": "moonshotai/Kimi-K2-Instruct-0905",
    "HuggingChat": "moonshotai/Kimi-K2-Instruct-0905",
    "LMArena": "kimi-k2-0905-preview",
    "KiloCode": "moonshotai/kimi-k2-0905",
    "OpenRouter": "moonshotai/kimi-k2-0905",
    "Puter": "openrouter:moonshotai/kimi-k2-0905"
  },
  "command-a-reasoning25": {
    "HuggingFace": "CohereLabs/command-a-reasoning-08-2025",
    "HuggingChat": "CohereLabs/command-a-reasoning-08-2025"
  },
  "glm-4.6": {
    "HuggingFace": "zai-org/GLM-4.6-FP8",
    "Airforce": "glm-4.6",
    "HuggingChat": "zai-org/GLM-4.6-FP8",
    "KiloCode": "z-ai/glm-4.6",
    "OpenRouter": "z-ai/glm-4.6",
    "Puter": "z-ai:z-ai/glm-4.6"
  },
  "tiny-aya-water": {
    "HuggingFace": "CohereLabs/tiny-aya-water",
    "HuggingChat": "CohereLabs/tiny-aya-water"
  },
  "minimax-m2.5": {
    "HuggingFace": "MiniMaxAI/MiniMax-M2.5",
    "HuggingChat": "MiniMaxAI/MiniMax-M2.5",
    "LMArena": "minimax-m2.5",
    "KiloCode": "minimax/minimax-m2.5",
    "OpenCode": "minimax-m2.5",
    "OpenRouter": "minimax/minimax-m2.5",
    "Puter": "openrouter:minimax/minimax-m2.5"
  },
  "hermes-3-llama-3.1-70b": {
    "HuggingFace": "NousResearch/Hermes-3-Llama-3.1-70B",
    "HuggingChat": "NousResearch/Hermes-3-Llama-3.1-70B",
    "KiloCode": "nousresearch/hermes-3-llama-3.1-70b",
    "OpenRouter": "nousresearch/hermes-3-llama-3.1-70b",
    "Puter": "openrouter:nousresearch/hermes-3-llama-3.1-70b"
  },
  "glm-4-32b-0414": {
    "HuggingFace": "zai-org/GLM-4-32B-0414",
    "HuggingChat": "zai-org/GLM-4-32B-0414"
  },
  "glm-4.5": {
    "HuggingFace": "zai-org/GLM-4.5",
    "Airforce": "glm-4.5",
    "GLM": "GLM-4.5",
    "KiloCode": "z-ai/glm-4.5",
    "OpenRouter": "z-ai/glm-4.5",
    "Puter": "z-ai:z-ai/glm-4.5"
  },
  "qwen-3-235b-a22b-thinking-2507": {
    "HuggingFace": "Qwen/Qwen3-235B-A22B-Thinking-2507",
    "Airforce": "qwen3-235b-a22b-thinking-2507",
    "HuggingChat": "Qwen/Qwen3-235B-A22B-Thinking-2507",
    "LMArena": "qwen3-235b-a22b-thinking-2507",
    "KiloCode": "qwen/qwen3-235b-a22b-thinking-2507",
    "OpenRouter": "qwen/qwen3-235b-a22b-thinking-2507",
    "Puter": "openrouter:qwen/qwen3-235b-a22b-thinking-2507"
  },
  "ernie-4.5-vl-424b-a47b-base-pt": {
    "HuggingFace": "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT",
    "HuggingChat": "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT"
  },
  "minimax-m1-80k": {
    "HuggingFace": "MiniMaxAI/MiniMax-M1-80k",
    "HuggingChat": "MiniMaxAI/MiniMax-M1-80k"
  },
  "deepseek-v3.1": {
    "HuggingFace": "deepseek-ai/DeepSeek-V3.1",
    "Airforce": "deepseek-v3.1",
    "G4FSpace": "srv_msu3vtvl920c386aa8a4:deepseek-ai/DeepSeek-V3.1",
    "HuggingChat": "deepseek-ai/DeepSeek-V3.1",
    "Puter": "infron:deepseek/deepseek-v3.1"
  },
  "glm-4.5v": {
    "HuggingFace": "zai-org/GLM-4.5V-FP8",
    "Airforce": "glm-4.5v",
    "HuggingChat": "zai-org/GLM-4.5V",
    "KiloCode": "z-ai/glm-4.5v",
    "OpenRouter": "z-ai/glm-4.5v",
    "Puter": "openrouter:z-ai/glm-4.5v"
  },
  "qwen-3-next-80b-a3b": {
    "HuggingFace": "Qwen/Qwen3-Next-80B-A3B-Instruct",
    "Airforce": "qwen3-next-80b-a3b-instruct",
    "HuggingChat": "Qwen/Qwen3-Next-80B-A3B-Instruct",
    "LMArena": "qwen3-next-80b-a3b-instruct",
    "KiloCode": "qwen/qwen3-next-80b-a3b-instruct",
    "OpenRouter": "qwen/qwen3-next-80b-a3b-instruct",
    "Puter": "openrouter:qwen/qwen3-next-80b-a3b-instruct"
  },
  "glm-4.7": {
    "HuggingFace": "zai-org/GLM-4.7",
    "Airforce": "glm-4.7",
    "GLM": "GLM-4.7",
    "HuggingChat": "zai-org/GLM-4.7",
    "LMArena": "glm-4.7",
    "KiloCode": "z-ai/glm-4.7",
    "OpenRouter": "z-ai/glm-4.7",
    "Puter": "z-ai:z-ai/glm-4.7"
  },
  "deepseek-v3.1-terminus": {
    "HuggingFace": "deepseek-ai/DeepSeek-V3.1-Terminus",
    "Airforce": "deepseek-v3.1-terminus",
    "HuggingChat": "deepseek-ai/DeepSeek-V3.1-Terminus",
    "KiloCode": "deepseek/deepseek-v3.1-terminus",
    "OpenRouter": "deepseek/deepseek-v3.1-terminus",
    "Puter": "openrouter:deepseek/deepseek-v3.1-terminus"
  },
  "qwen-3-vl-235b-a22b-thinking": {
    "HuggingFace": "Qwen/Qwen3-VL-235B-A22B-Thinking",
    "HuggingChat": "Qwen/Qwen3-VL-235B-A22B-Thinking",
    "LMArena": "qwen3-vl-235b-a22b-thinking",
    "KiloCode": "qwen/qwen3-vl-235b-a22b-thinking",
    "OpenRouter": "qwen/qwen3-vl-235b-a22b-thinking",
    "Puter": "openrouter:qwen/qwen3-vl-235b-a22b-thinking"
  },
  "deepseek-v3.2-exp": {
    "HuggingFace": "deepseek-ai/DeepSeek-V3.2-Exp",
    "Airforce": "deepseek-v3.2-exp",
    "HuggingChat": "deepseek-ai/DeepSeek-V3.2-Exp",
    "KiloCode": "deepseek/deepseek-v3.2-exp",
    "OpenRouter": "deepseek/deepseek-v3.2-exp",
    "Puter": "openrouter:deepseek/deepseek-v3.2-exp"
  },
  "glm-5": {
    "HuggingFace": "zai-org/GLM-5",
    "Airforce": "glm-5",
    "HuggingChat": "zai-org/GLM-5",
    "LMArena": "glm-5",
    "KiloCode": "z-ai/glm-5",
    "OpenCode": "glm-5",
    "OpenRouter": "z-ai/glm-5",
    "Puter": "z-ai:z-ai/glm-5"
  },
  "glm-4.6v-flash": {
    "HuggingFace": "zai-org/GLM-4.6V-Flash",
    "G4FSpace": "srv_mp5miql908c8738d71be:community/MarcosFRG/glm-4.6v-flash",
    "HuggingChat": "zai-org/GLM-4.6V-Flash",
    "Pollinations": "community/MarcosFRG/glm-4.6v-flash",
    "Puter": "infron:z-ai/glm-4.6v-flash"
  },
  "minimax-m2": {
    "HuggingFace": "MiniMaxAI/MiniMax-M2",
    "Airforce": "minimax-m2",
    "HuggingChat": "MiniMaxAI/MiniMax-M2",
    "LMArena": "minimax-m2-preview",
    "KiloCode": "minimax/minimax-m2",
    "OpenRouter": "minimax/minimax-m2",
    "Puter": "openrouter:minimax/minimax-m2"
  },
  "command-r7b24": {
    "HuggingFace": "CohereLabs/c4ai-command-r7b-12-2024",
    "HuggingSpace": "command-r7b-12-2024",
    "CohereForAI_C4AI_Command": "command-r7b-12-2024",
    "HuggingChat": "CohereLabs/c4ai-command-r7b-12-2024",
    "KiloCode": "cohere/command-r7b-12-2024",
    "OpenRouter": "cohere/command-r7b-12-2024",
    "Puter": "openrouter:cohere/command-r7b-12-2024"
  },
  "gemma-sea-lion-v4-27b-it": {
    "HuggingFace": "aisingapore/Gemma-SEA-LION-v4-27B-IT",
    "GeminiPro": "gemma-sea-lion-v4-27b-it",
    "HuggingChat": "aisingapore/Gemma-SEA-LION-v4-27B-IT"
  },
  "minimax-m2.1": {
    "HuggingFace": "MiniMaxAI/MiniMax-M2.1",
    "Airforce": "minimax-m2.1",
    "HuggingChat": "MiniMaxAI/MiniMax-M2.1",
    "LMArena": "minimax-m2.1-preview",
    "KiloCode": "minimax/minimax-m2.1",
    "OpenRouter": "minimax/minimax-m2.1",
    "Puter": "openrouter:minimax/minimax-m2.1"
  },
  "command-r7b-arabic25": {
    "HuggingFace": "CohereLabs/c4ai-command-r7b-arabic-02-2025",
    "HuggingSpace": "command-r7b-arabic-02-2025",
    "CohereForAI_C4AI_Command": "command-r7b-arabic-02-2025",
    "HuggingChat": "CohereLabs/c4ai-command-r7b-arabic-02-2025"
  },
  "apertus-8b-2509": {
    "HuggingFace": "swiss-ai/Apertus-8B-Instruct-2509",
    "HuggingChat": "swiss-ai/Apertus-8B-Instruct-2509"
  },
  "aya-vision-32b": {
    "HuggingFace": "CohereLabs/aya-vision-32b",
    "HuggingChat": "CohereLabs/aya-vision-32b"
  },
  "qwen-3-vl-30b-a3b": {
    "HuggingFace": "Qwen/Qwen3-VL-30B-A3B-Instruct",
    "Airforce": "qwen3-vl-30b-a3b-instruct",
    "HuggingChat": "Qwen/Qwen3-VL-30B-A3B-Instruct",
    "KiloCode": "qwen/qwen3-vl-30b-a3b-instruct",
    "OpenRouter": "qwen/qwen3-vl-30b-a3b-instruct",
    "Puter": "openrouter:qwen/qwen3-vl-30b-a3b-instruct"
  },
  "command-a25": {
    "HuggingFace": "CohereLabs/c4ai-command-a-03-2025",
    "HuggingSpace": "command-a-03-2025",
    "CohereForAI_C4AI_Command": "command-a-03-2025",
    "HuggingChat": "CohereLabs/c4ai-command-a-03-2025",
    "Puter": "infron:cohere/command-a-03-2025"
  },
  "qwen-sea-lion-v4-32b-it": {
    "HuggingFace": "aisingapore/Qwen-SEA-LION-v4-32B-IT",
    "HuggingChat": "aisingapore/Qwen-SEA-LION-v4-32B-IT"
  },
  "command-a-vision25": {
    "HuggingFace": "CohereLabs/command-a-vision-07-2025",
    "HuggingChat": "CohereLabs/command-a-vision-07-2025"
  },
  "command-a-translate25": {
    "HuggingFace": "CohereLabs/command-a-translate-08-2025",
    "HuggingChat": "CohereLabs/command-a-translate-08-2025"
  },
  "tiny-aya-global": {
    "HuggingFace": "CohereLabs/tiny-aya-global",
    "HuggingChat": "CohereLabs/tiny-aya-global"
  },
  "qwen-3-4b-thinking-2507": {
    "HuggingFace": "Qwen/Qwen3-4B-Thinking-2507",
    "HuggingChat": "Qwen/Qwen3-4B-Thinking-2507"
  },
  "tiny-aya-earth": {
    "HuggingFace": "CohereLabs/tiny-aya-earth",
    "HuggingChat": "CohereLabs/tiny-aya-earth"
  },
  "glm-4.6v": {
    "HuggingFace": "zai-org/GLM-4.6V-FP8",
    "GLM": "GLM-4.6V",
    "HuggingChat": "zai-org/GLM-4.6V-FP8",
    "KiloCode": "z-ai/glm-4.6v",
    "OpenRouter": "z-ai/glm-4.6v",
    "Puter": "openrouter:z-ai/glm-4.6v"
  },
  "tiny-aya-fire": {
    "HuggingFace": "CohereLabs/tiny-aya-fire",
    "HuggingChat": "CohereLabs/tiny-aya-fire"
  },
  "command-r": {
    "HuggingSpace": "command-r-08-2024",
    "CohereForAI_C4AI_Command": "command-r-08-2024",
    "Puter": [
      "openrouter:cohere/command-r-08-2024",
      "openrouter:cohere/command-r",
      "openrouter:cohere/command-r-03-2024"
    ]
  },
  "command-r-plus": {
    "HuggingSpace": [
      "command-r-plus-08-2024",
      "command-r-plus"
    ],
    "CohereForAI_C4AI_Command": [
      "command-r-plus-08-2024",
      "command-r-plus"
    ],
    "Puter": [
      "openrouter:cohere/command-r-plus-08-2024",
      "openrouter:cohere/command-r-plus",
      "openrouter:cohere/command-r-plus-04-2024"
    ]
  },
  "command-r-plus24": {
    "HuggingSpace": "command-r-plus-08-2024",
    "CohereForAI_C4AI_Command": "command-r-plus-08-2024",
    "KiloCode": "cohere/command-r-plus-08-2024",
    "OpenRouter": "cohere/command-r-plus-08-2024",
    "Puter": "openrouter:cohere/command-r-plus-08-2024"
  },
  "flux-dev": {
    "HuggingSpace": "black-forest-labs-flux-1-dev",
    "BlackForestLabs_Flux1Dev": "black-forest-labs-flux-1-dev",
    "HuggingFaceMedia": "black-forest-labs/FLUX.1-dev",
    "Pollinations": "flux"
  },
  "flux-kontext-dev": {
    "HuggingSpace": "flux-kontext-dev",
    "BlackForestLabs_Flux1KontextDev": "flux-kontext-dev"
  },
  "perplexity": {
    "Perplexity": "perplexity"
  },
  "pplx_pro": {
    "Perplexity": "pplx_pro"
  },
  "video": {
    "Video": "video"
  }
}
models_count = {
  "default": 16,
  "gpt-4": 11,
  "gpt-4o": 11,
  "gpt-4o-mini": 8,
  "gpt-4o-mini-tts": 2,
  "o1": 10,
  "o1-mini": 4,
  "o3-mini": 7,
  "o3-mini-high": 5,
  "o4-mini": 6,
  "o4-mini-high": 4,
  "gpt-4.1": 7,
  "gpt-4.1-mini": 7,
  "gpt-4.1-nano": 5,
  "gpt-4.5": 2,
  "gpt-oss-120b": 12,
  "dall-e-3": 5,
  "gpt-image": 3,
  "meta-ai": 2,
  "llama-2-70b": 4,
  "llama-3-8b": 5,
  "llama-3-70b": 5,
  "llama-3.1-8b": 8,
  "llama-3.1-70b": 5,
  "llama-3.1-405b": 3,
  "llama-3.2-3b": 5,
  "llama-3.2-90b": 2,
  "llama-4-scout": 6,
  "llama-4-maverick": 5,
  "mixtral-8x7b": 2,
  "mistral-small-3.1-24b": 6,
  "hermes-2-dpo": 2,
  "gemini-2.5-flash": 9,
  "gemini-2.5-pro": 8,
  "gemini-3-pro-preview": 2,
  "gemini-3.1-pro": 8,
  "gemini-3.1-flash-lite": 9,
  "gemini-3.5-flash": 10,
  "gemini-3.5-flash-thinking": 2,
  "gemini-auto": 2,
  "gemini-3.5-flash-thinking-lite": 2,
  "gemini-flash-lite": 4,
  "command-r7b": 3,
  "command-a": 5,
  "qwen-2.5-coder-32b": 8,
  "qwen-2.5-vl-72b": 6,
  "qwen-3-235b": 2,
  "qwen-3-32b": 7,
  "qwq-32b": 6,
  "deepseek-v3": 3,
  "deepseek-r1": 10,
  "deepseek-r1-distill-llama-70b": 7,
  "deepseek-r1-distill-qwen-1.5b": 2,
  "deepseek-r1-distill-qwen-14b": 4,
  "grok-2": 2,
  "grok-3": 2,
  "kimi-k2": 7,
  "sonar": 3,
  "sonar-pro": 3,
  "sonar-reasoning": 2,
  "sonar-reasoning-pro": 3,
  "r1-1776": 3,
  "nemotron-70b": 3,
  "sdxl-turbo": 3,
  "sd-3.5-large": 3,
  "flux": 6,
  "flux-pro": 3,
  "flux-kontext": 2,
  "glm-5.2": 13,
  "kimi-k2.7-code": 11,
  "nemotron-3-ultra-550b-a55b": 10,
  "deepseek-v4-flash": 12,
  "deepseek-v4-pro": 10,
  "kimi-k2.6": 11,
  "mimo-v2.5-pro": 9,
  "qwen-3.6-35b-a3b": 8,
  "glm-5.1": 10,
  "qwen-3.5-397b-a17b": 9,
  "gemma-4-26b-a4b-it": 9,
  "gemma-4-31b-it": 9,
  "glm-5": 8,
  "minimax-m2.5": 7,
  "qwen-3-max": 7,
  "qwen-3-max-thinking": 5,
  "kimi-k2.5": 7,
  "glm-4.7-flash": 8,
  "deepseek-v3.2": 7,
  "inkling": 7,
  "ternary-bonsai-27b-gguf": 2,
  "qwen-3.6-27b": 7,
  "hy3": 6,
  "ornith-1.0-35b": 2,
  "apertus-v1.5-70b": 2,
  "minimax-m3": 11,
  "apertus-v1.5-8b": 2,
  "qwen-3.5-9b": 6,
  "qwen-3-8b": 6,
  "gpt-oss-20b": 12,
  "qwen-3.5-27b": 7,
  "qwen-3-coder-30b-a3b": 6,
  "mimo-v2.5": 9,
  "qwen-3-coder-next": 5,
  "gemma-3-4b-it": 7,
  "qwen-3.5-122b-a10b": 8,
  "ling-2.6-1t": 4,
  "qwen-3-4b-2507": 2,
  "step-3.7-flash": 6,
  "glm-4.5-air": 7,
  "qwen-3-14b": 6,
  "qwen-3-next-80b-a3b": 7,
  "qwen-2.5-coder-7b": 3,
  "nemotron-3-ultra-550b-a55b-nvfp4": 2,
  "qwen-3.5-35b-a3b": 7,
  "gemma-3-27b-it": 7,
  "gemma-3-12b-it": 7,
  "phi-4": 5,
  "qwen-3-vl-30b-a3b": 6,
  "ternary-bonsai-27b-awq-4bit": 2,
  "kimi-k2-0905": 6,
  "qwen-2.5-7b": 5,
  "qwen-3-vl-235b-a22b": 7,
  "llama-3.3-70b": 8,
  "qwen-3-coder-480b-a35b": 5,
  "gpt-oss-safeguard-20b": 7,
  "command-r7b24": 7,
  "qwen-3-235b-a22b-2507": 7,
  "llama-4-scout-17b-16e": 2,
  "step-3.5-flash": 7,
  "qwen-2.5-coder-3b": 2,
  "l3-8b-stheno-v3.2": 2,
  "deepseek-r1-distill-qwen-7b": 2,
  "llama-guard-4-12b": 6,
  "qwen-3-4b-thinking-2507": 2,
  "glm-4.7": 8,
  "gemma-sea-lion-v4-27b-it": 3,
  "command-a25": 5,
  "deepseek-r1-distill-llama-8b": 3,
  "apertus-8b-2509": 2,
  "tiny-aya-global": 2,
  "qwen-3-235b-a22b": 7,
  "bielik-11b-v3.0": 2,
  "tiny-aya-earth": 2,
  "minimax-m2.7": 9,
  "llama-4-maverick-17b-128e": 2,
  "deepseek-v3-0324": 3,
  "ernie-4.5-vl-424b-a47b-base-pt": 2,
  "glm-4-32b-0414": 2,
  "deepseek-r1-0528": 6,
  "qwen-3-235b-a22b-thinking-2507": 7,
  "deepseek": 4,
  "glm-4.5": 6,
  "glm-4.5v": 6,
  "wizardlm-2-8x22b": 5,
  "qwen-2.5-72b": 4,
  "glm-4.6": 6,
  "glm-4.6v-flash": 5,
  "l3-8b-lunaris": 2,
  "deepseek-v3.1": 5,
  "glm-4.6v": 6,
  "minimax-m1-80k": 2,
  "deepseek-v3.1-terminus": 6,
  "command-r24": 7,
  "deepseek-v3.2-exp": 6,
  "aya-expanse-32b": 2,
  "aya-vision-32b": 2,
  "minimax-m2": 7,
  "command-r7b-arabic25": 4,
  "command-a-vision25": 2,
  "minimax-m2.1": 7,
  "command-a-reasoning25": 2,
  "gemma-3n-e4b-it": 7,
  "command-a-translate25": 2,
  "qwen-3-vl-235b-a22b-thinking": 6,
  "gemma-4-31b-it-pearl": 3,
  "tiny-aya-water": 2,
  "apertus-70b-2509": 2,
  "autoglm-phone-9b-multilingual": 2,
  "tiny-aya-fire": 2,
  "qwen-sea-lion-v4-32b-it": 2,
  "olmo-3-7b": 2,
  "eurollm-22b-2512": 2,
  "command-r": 3,
  "command-r-plus": 3,
  "command-r-plus24": 5,
  "flux-dev": 4,
  "flux-kontext-dev": 2,
  "perplexity": 2,
  "gemini-3.6-flash": 11,
  "gemini-3.7-flash": 11,
  "gemini-3.8-flash": 10,
  "gemini-3.8-pro": 2,
  "gemini-3.5-flash-lite": 9,
  "deepseek-v4.1-flash": 9,
  "glm-5.3": 12,
  "glm-5.3-flash": 12,
  "kimi-k3": 11,
  "qwen-3.8-2.4t-a95b": 6,
  "deepseek-v4-pro-0813": 8,
  "deepseek-v4-flash-0731": 8,
  "nemotron-3-super-120b-a12b": 7,
  "qwen-3.8-27b": 10,
  "deepseek-v4-flash-vision-exp": 7,
  "muse-glimmer-30b": 8,
  "ling-3.0-flash-vl": 7,
  "ling-3.0-flash-fin": 7,
  "nemotron-3.5-lightning-30b-a3b": 4,
  "ling-3.0-flash": 5,
  "granite-4.2-3b": 2,
  "granite-4.2-8b": 5,
  "inkling-small": 7,
  "qwen-3-30b-a3b": 8,
  "granite-4.2-30b": 2,
  "hermes-3-llama-3.1-70b": 5
}
parents = {
  "HuggingSpace": [
    "BlackForestLabs_Flux1Dev",
    "BlackForestLabs_Flux1KontextDev",
    "CohereForAI_C4AI_Command",
    "StabilityAI_SD35Large"
  ],
  "Copilot": [
    "CopilotAccount",
    "CopilotSession"
  ],
  "HuggingFace": [
    "HuggingFaceMedia"
  ],
  "MetaAI": [
    "MetaAIAccount"
  ],
  "OpenaiChat": [
    "OpenaiAccount"
  ],
  "Pollinations": [
    "PollinationsAudio",
    "PollinationsImage"
  ]
}
model_aliases = {
  "": "default",
  "chat": "gpt-4o-mini",
  "Copilot": "dall-e-3",
  "openai/gpt-4": "gpt-4",
  "openrouter:openai/gpt-4": "gpt-4",
  "openai/gpt-4o-2024-05-13": "gpt-4o",
  "openrouter:openai/gpt-4o-2024-11-20": "gpt-4o",
  "openai/gpt-4o-mini-2024-07-18": "gpt-4o-mini",
  "openrouter:openai/gpt-4o-mini-2024-07-18": "gpt-4o-mini",
  "coral": "gpt-4o-mini-tts",
  "Think Deeper": "o1",
  "reasoning": "grok-3-r1",
  "openai/o1": "o1",
  "openai:openai/o1": "o1",
  "openai:openai/o1-mini": "o1-mini",
  "o3-mini-2025-01-31": "o3-mini",
  "openai/o3-mini": "o3-mini",
  "openai:openai/o3-mini": "o3-mini",
  "openai/o3-mini-high": "o3-mini-high",
  "openrouter:openai/o3-mini-high": "o3-mini-high",
  "o4-mini-2025-04-16": "o4-mini",
  "openai/o4-mini": "o4-mini",
  "openai:openai/o4-mini": "o4-mini",
  "openai/o4-mini-high": "o4-mini-high",
  "openrouter:openai/o4-mini-high": "o4-mini-high",
  "gpt-4-1": "gpt-4.1",
  "gpt-4.1-2025-04-14": "gpt-4.1",
  "openai/gpt-4.1": "gpt-4.1",
  "openai:openai/gpt-4.1": "gpt-4.1",
  "gpt-4-1-mini": "gpt-4.1-mini",
  "gpt-4.1-mini-2025-04-14": "gpt-4.1-mini",
  "openai/gpt-4.1-mini": "gpt-4.1-mini",
  "openai:openai/gpt-4.1-mini": "gpt-4.1-mini",
  "openai-fast": "gpt-4.1-nano",
  "openai/gpt-4.1-nano": "gpt-4.1-nano",
  "openai:openai/gpt-4.1-nano": "gpt-4.1-nano",
  "gpt-4-5": "gpt-4.5",
  "openai:openai/gpt-4.5-preview": "gpt-4.5",
  "openai/gpt-oss-120b": "gpt-oss-120b",
  "@cf/openai/gpt-oss-120b": "gpt-oss-120b",
  "gpt-oss:120b": "gpt-oss-120b",
  "Catniti/gpt-oss-120b": "gpt-oss-120b",
  "togetherai:openai/gpt-oss-120b": "gpt-oss-120b",
  "gptimage": "gpt-image",
  "meta/llama2-70b": "llama-2-70b",
  "openrouter:meta-llama/llama-2-70b-chat": "llama-2-70b",
  "@hf/meta-llama/meta-llama-3-8b-instruct": "llama-3-8b",
  "llama-3-8b-instruct": "llama-3-8b",
  "openrouter:meta-llama/llama-3-8b-instruct": "llama-3-8b",
  "llama-3-70b-instruct": "llama-3-70b",
  "openrouter:meta-llama/llama-3-70b-instruct": "llama-3-70b",
  "meta/meta-llama-3-70b-instruct": "llama-3-70b",
  "meta-llama/Llama-3.1-8B-Instruct": "llama-3.1-8b",
  "llama3.1-8b": "llama-3.1-8b",
  "@cf/meta/llama-3.1-8b-instruct-fp8": "llama-3.1-8b",
  "hf:meta-llama/Llama-3.1-8B-Instruct": "llama-3.1-8b",
  "meta/llama-3.1-8b-instruct": "llama-3.1-8b",
  "meta-llama/llama-3.1-8b-instruct": "llama-3.1-8b",
  "llama3.1-70b": "llama-3.1-70b",
  "hf:meta-llama/Llama-3.1-70B-Instruct": "llama-3.1-70b",
  "meta/llama-3.1-70b-instruct": "llama-3.1-70b",
  "meta-llama/llama-3.1-70b-instruct": "llama-3.1-70b",
  "openrouter:meta-llama/llama-3.1-70b-instruct": "llama-3.1-70b",
  "hf:meta-llama/Llama-3.1-405B-Instruct": "llama-3.1-405b",
  "@cf/meta/llama-3.2-3b-instruct": "llama-3.2-3b",
  "hf:meta-llama/Llama-3.2-3B-Instruct": "llama-3.2-3b",
  "meta/llama-3.2-3b-instruct": "llama-3.2-3b",
  "meta-llama/llama-3.2-3b-instruct": "llama-3.2-3b",
  "openrouter:meta-llama/llama-3.2-90b-vision-instruct": "llama-3.2-90b",
  "llama-scout": "llama-4-scout",
  "@cf/meta/llama-4-scout-17b-16e-instruct": "llama-4-scout",
  "meta-llama/llama-4-scout": "llama-4-scout",
  "meta-llama/llama-4-maverick": "llama-4-maverick",
  "llama-maverick": "llama-4-maverick",
  "mixtral-8x7b-32768": "mixtral-8x7b",
  "mistral-small": "mistral-small-3.1-24b",
  "mistral-small-3.1-24b-instruct": "mistral-small-3.1-24b",
  "@cf/mistralai/mistral-small-3.1-24b-instruct": "mistral-small-3.1-24b",
  "mistralai/mistral-small-3.1-24b-instruct": "mistral-small-3.1-24b",
  "openrouter:mistralai/mistral-small-3.1-24b-instruct": "mistral-small-3.1-24b",
  "openrouter:nousresearch/nous-hermes-2-mixtral-8x7b-dpo": "hermes-2-dpo",
  "google/gemini-2.5-flash": "gemini-2.5-flash",
  "openrouter:google/gemini-2.5-flash-preview": "gemini-2.5-flash",
  "google/gemini-2.5-pro-preview-05-06": "gemini-2.5-pro",
  "gemini-large": "gemini-3.1-pro",
  "gemini-3.1-pro-preview": "gemini-3.1-pro",
  "google/gemini-3.1-pro-preview": "gemini-3.1-pro",
  "openrouter:google/gemini-3.1-pro-preview": "gemini-3.1-pro",
  "google/gemini-3.1-flash-lite-preview": "gemini-3.1-flash-lite",
  "gemini-flash-lite-3.5": "gemini-flash-lite",
  "openrouter:google/gemini-3.1-flash-lite-preview": "gemini-3.1-flash-lite",
  "google/gemini-3.5-flash": "gemini-3.5-flash",
  "gemini": "gemini-3.5-flash",
  "openrouter:google/gemini-3.5-flash": "gemini-3.5-flash",
  "openrouter:cohere/command-r7b-12-2024": "command-r7b24",
  "command-a-03-2025": "command-a25",
  "cohere/command-a": "command-a",
  "openrouter:cohere/command-a": "command-a",
  "Qwen/Qwen2.5-Coder-32B-Instruct": "qwen-2.5-coder-32b",
  "@cf/qwen/qwen2.5-coder-32b-instruct": "qwen-2.5-coder-32b",
  "hf:Qwen/Qwen2.5-Coder-32B-Instruct": "qwen-2.5-coder-32b",
  "qwen/qwen-2.5-coder-32b-instruct": "qwen-2.5-coder-32b",
  "qwen-3-coder": "qwen-2.5-coder-32b",
  "Qwen/Qwen2.5-VL-72B-Instruct": "qwen-2.5-vl-72b",
  "qwen/qwen2.5-vl-72b-instruct": "qwen-2.5-vl-72b",
  "Qwen/Qwen3-32B": "qwen-3-32b",
  "qwen3-32b": "qwen-3-32b",
  "qwen/qwen3-32b": "qwen-3-32b",
  "@cf/qwen/qwq-32b": "qwq-32b",
  "hf:Qwen/QwQ-32B-Preview": "qwq-32b",
  "openrouter:deepseek/deepseek-v3-base:free": "deepseek-v3",
  "deepseek-reasoning": "deepseek-r1",
  "deepseek-ai/DeepSeek-R1": "deepseek-r1",
  "deepseek/deepseek-r1": "deepseek-r1",
  "v3": "deepseek",
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": "deepseek-r1-distill-llama-70b",
  "deepseek/deepseek-r1-distill-llama-70b": "deepseek-r1-distill-llama-70b",
  "openrouter:deepseek/deepseek-r1-distill-qwen-1.5b": "deepseek-r1-distill-qwen-1.5b",
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": "deepseek-r1-distill-qwen-14b",
  "x-ai:x-ai/grok-3": "grok-3",
  "grok-3-reasoning": "grok-3-r1",
  "moonshotai/Kimi-K2-Instruct": "kimi-k2",
  "moonshotai/kimi-k2": "kimi-k2",
  "openrouter:moonshotai/kimi-k2": "kimi-k2",
  "openrouter:perplexity/sonar": "sonar",
  "perplexity/sonar": "sonar",
  "perplexity-fast": "sonar",
  "openrouter:perplexity/sonar-pro": "sonar-pro",
  "perplexity/sonar-pro": "sonar-pro",
  "openrouter:perplexity/sonar-reasoning": "sonar-reasoning",
  "perplexity-reasoning": "sonar-reasoning-pro",
  "openrouter:perplexity/sonar-reasoning-pro": "sonar-reasoning-pro",
  "perplexity/sonar-reasoning-pro": "sonar-reasoning-pro",
  "openrouter:perplexity/r1-1776": "r1-1776",
  "openrouter:nvidia/llama-3.1-nemotron-70b-instruct": "nemotron-70b",
  "stabilityai/sdxl-turbo": "sdxl-turbo",
  "turbo": "sdxl-turbo",
  "stabilityai/stable-diffusion-3.5-large": "sd-3.5-large",
  "stabilityai-stable-diffusion-3-5-large": "sd-3.5-large",
  "black-forest-labs/FLUX.1-dev": "flux-dev",
  "black-forest-labs-flux-1-dev": "flux-dev",
  "kontext": "flux-kontext",
  "zai-org/GLM-5.2": "glm-5.2",
  "zai-org/GLM-5.2-FP8": "glm-5.2",
  "@cf/zai-org/glm-5.2": "glm-5.2",
  "GLM-5.2": "glm-5.2",
  "z-ai/glm-5.2": "glm-5.2",
  "glm": "glm-5.2",
  "z-ai:z-ai/glm-5.2": "glm-5.2",
  "moonshotai/Kimi-K2.7-Code": "kimi-k2.7-code",
  "@cf/moonshotai/kimi-k2.7-code": "kimi-k2.7-code",
  "moonshotai/kimi-k2.7-code": "kimi-k2.7-code",
  "kimi-code": "kimi-k2.7-code",
  "togetherai:moonshotai/kimi-k2.7-code": "kimi-k2.7-code",
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": "nemotron-3-ultra-550b-a55b",
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16": "nemotron-3-ultra-550b-a55b",
  "deepseek-ai/DeepSeek-V4-Flash": "deepseek-v4-flash",
  "deepseek-ai/deepseek-v4-flash": "deepseek-v4-flash",
  "deepseek/deepseek-v4-flash": "deepseek-v4-flash",
  "deepseek:deepseek/deepseek-v4-flash": "deepseek-v4-flash",
  "deepseek-ai/DeepSeek-V4-Pro": "deepseek-v4-pro",
  "deepseek-ai/deepseek-v4-pro": "deepseek-v4-pro",
  "deepseek/deepseek-v4-pro": "deepseek-v4-pro",
  "deepseek-pro": "deepseek-v4-pro",
  "deepseek:deepseek/deepseek-v4-pro": "deepseek-v4-pro",
  "moonshotai/Kimi-K2.6": "kimi-k2.6",
  "@cf/moonshotai/kimi-k2.6": "kimi-k2.6",
  "moonshotai/kimi-k2.6": "kimi-k2.6",
  "kimi": "kimi-k2.6",
  "moonshotai:moonshotai/kimi-k2.6": "kimi-k2.6",
  "XiaomiMiMo/MiMo-V2.5-Pro": "mimo-v2.5-pro",
  "xiaomi/mimo-v2.5-pro": "mimo-v2.5-pro",
  "openrouter:xiaomi/mimo-v2.5-pro": "mimo-v2.5-pro",
  "Qwen/Qwen3.6-35B-A3B": "qwen-3.6-35b-a3b",
  "qwen3.6-35b-a3b": "qwen-3.6-35b-a3b",
  "qwen/qwen3.6-35b-a3b": "qwen-3.6-35b-a3b",
  "alibaba:qwen/qwen3.6-35b-a3b": "qwen-3.6-35b-a3b",
  "zai-org/GLM-5.1": "glm-5.1",
  "zai-org/GLM-5.1-FP8": "glm-5.1",
  "GLM-5.1": "glm-5.1",
  "z-ai/glm-5.1": "glm-5.1",
  "z-ai:z-ai/glm-5.1": "glm-5.1",
  "Qwen/Qwen3.5-397B-A17B": "qwen-3.5-397b-a17b",
  "qwen3.5-397b-a17b": "qwen-3.5-397b-a17b",
  "qwen/qwen3.5-397b-a17b": "qwen-3.5-397b-a17b",
  "alibaba:qwen/qwen3.5-397b-a17b": "qwen-3.5-397b-a17b",
  "google/gemma-4-26B-A4B-it": "gemma-4-26b-a4b-it",
  "@cf/google/gemma-4-26b-a4b-it": "gemma-4-26b-a4b-it",
  "google/gemma-4-26b-a4b-it:free": "gemma-4-26b-a4b-it",
  "gemma": "gemma-4-26b-a4b-it",
  "openrouter:google/gemma-4-26b-a4b-it:free": "gemma-4-26b-a4b-it",
  "google/gemma-4-31B-it": "gemma-4-31b-it",
  "google/gemma-4-31b-it": "gemma-4-31b-it",
  "google/gemma-4-31b-it:free": "gemma-4-31b-it",
  "gemma-4-31b": "gemma-4-31b-it",
  "togetherai:google/gemma-4-31b-it": "gemma-4-31b-it",
  "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B": "nemotron-3-super-120b-a12b",
  "zai-org/GLM-5": "glm-5",
  "z-ai/glm-5": "glm-5",
  "z-ai:z-ai/glm-5": "glm-5",
  "MiniMaxAI/MiniMax-M2.5": "minimax-m2.5",
  "minimax/minimax-m2.5": "minimax-m2.5",
  "minimax:minimax/minimax-m2.5": "minimax-m2.5",
  "Qwen/Qwen3-Max": "qwen-3-max",
  "qwen3-max": "qwen-3-max",
  "qwen3-max-2025-09-26": "qwen-3-max",
  "qwen/qwen3-max": "qwen-3-max",
  "alibaba:qwen/qwen3-max": "qwen-3-max",
  "qwen3-max-2026-01-23": "qwen-3-max",
  "Qwen/Qwen3-Max-Thinking": "qwen-3-max-thinking",
  "qwen3-max-thinking": "qwen-3-max-thinking",
  "qwen/qwen3-max-thinking": "qwen-3-max-thinking",
  "openrouter:qwen/qwen3-max-thinking": "qwen-3-max-thinking",
  "moonshotai/Kimi-K2.5": "kimi-k2.5",
  "moonshotai/kimi-k2.5": "kimi-k2.5",
  "moonshotai:moonshotai/kimi-k2.5": "kimi-k2.5",
  "zai-org/GLM-4.7-Flash": "glm-4.7-flash",
  "@cf/zai-org/glm-4.7-flash": "glm-4.7-flash",
  "z-ai/glm-4.7-flash": "glm-4.7-flash",
  "Catniti/glm-4.7-flash": "glm-4.7-flash",
  "z-ai:z-ai/glm-4.7-flash": "glm-4.7-flash",
  "deepseek-ai/DeepSeek-V3.2": "deepseek-v3.2",
  "deepseek/deepseek-v3.2": "deepseek-v3.2",
  "Minor-fun/deepseek-v3.2": "deepseek-v3.2",
  "openrouter:deepseek/deepseek-v3.2": "deepseek-v3.2",
  "black-forest-labs/FLUX-2-klein-4b": "flux-2-klein-4b",
  "black-forest-labs/FLUX-2-klein-9b": "flux-2-klein-9b",
  "thinkingmachines/Inkling": "inkling",
  "thinkingmachines/inkling": "inkling",
  "togetherai:thinkingmachines/inkling": "inkling",
  "prism-ml/Ternary-Bonsai-27B-gguf": "ternary-bonsai-27b-gguf",
  "Qwen/Qwen3.6-27B": "qwen-3.6-27b",
  "qwen/qwen3.6-27b": "qwen-3.6-27b",
  "qwen3.6-27b": "qwen-3.6-27b",
  "alibaba:qwen/qwen3.6-27b": "qwen-3.6-27b",
  "tencent/Hy3": "hy3",
  "tencent/hy3-preview": "hy3",
  "openrouter:tencent/hy3-preview": "hy3",
  "deepreinforce-ai/Ornith-1.0-35B-FP8": "ornith-1.0-35b",
  "swiss-ai/Apertus-v1.5-70B": "apertus-v1.5-70b",
  "MiniMaxAI/MiniMax-M3": "minimax-m3",
  "MiniMax-M3": "minimax-m3",
  "minimaxai/minimax-m3": "minimax-m3",
  "minimax/minimax-m3": "minimax-m3",
  "minimax": "minimax-m3",
  "minimax:minimax/minimax-m3": "minimax-m3",
  "swiss-ai/Apertus-v1.5-8B": "apertus-v1.5-8b",
  "Qwen/Qwen3.5-9B": "qwen-3.5-9b",
  "qwen/qwen3.5-9b": "qwen-3.5-9b",
  "togetherai:qwen/qwen3.5-9b": "qwen-3.5-9b",
  "Qwen/Qwen3-8B": "qwen-3-8b",
  "qwen3-8b": "qwen-3-8b",
  "qwen/qwen3-8b": "qwen-3-8b",
  "openai/gpt-oss-20b": "gpt-oss-20b",
  "@cf/openai/gpt-oss-20b": "gpt-oss-20b",
  "gpt-oss:20b": "gpt-oss-20b",
  "openai/gpt-oss-20b:free": "gpt-oss-20b",
  "gpt-oss": "gpt-oss-20b",
  "togetherai:openai/gpt-oss-20b": "gpt-oss-20b",
  "Qwen/Qwen3.5-27B": "qwen-3.5-27b",
  "qwen3.5-27b": "qwen-3.5-27b",
  "qwen/qwen3.5-27b": "qwen-3.5-27b",
  "alibaba:qwen/qwen3.5-27b": "qwen-3.5-27b",
  "Qwen/Qwen3-Coder-30B-A3B-Instruct": "qwen-3-coder-30b-a3b",
  "qwen3-coder-30b-a3b": "qwen-3-coder-30b-a3b",
  "qwen/qwen3-coder-30b-a3b-instruct": "qwen-3-coder-30b-a3b",
  "alibaba:qwen/qwen3-coder-30b-a3b-instruct": "qwen-3-coder-30b-a3b",
  "XiaomiMiMo/MiMo-V2.5": "mimo-v2.5",
  "xiaomi/mimo-v2.5": "mimo-v2.5",
  "MarcosFRG/mimo-v2.5": "mimo-v2.5",
  "openrouter:xiaomi/mimo-v2.5": "mimo-v2.5",
  "Qwen/Qwen3-Coder-Next": "qwen-3-coder-next",
  "qwen/qwen3-coder-next": "qwen-3-coder-next",
  "openrouter:qwen/qwen3-coder-next": "qwen-3-coder-next",
  "google/gemma-3-4b-it": "gemma-3-4b-it",
  "openrouter:google/gemma-3-4b-it": "gemma-3-4b-it",
  "Qwen/Qwen3.5-122B-A10B": "qwen-3.5-122b-a10b",
  "qwen3.5-122b-a10b": "qwen-3.5-122b-a10b",
  "qwen/qwen3.5-122b-a10b": "qwen-3.5-122b-a10b",
  "alibaba:qwen/qwen3.5-122b-a10b": "qwen-3.5-122b-a10b",
  "inclusionAI/Ling-2.6-1T": "ling-2.6-1t",
  "inclusionai/ling-2.6-1t": "ling-2.6-1t",
  "openrouter:inclusionai/ling-2.6-1t": "ling-2.6-1t",
  "Qwen/Qwen3-4B-Instruct-2507": "qwen-3-4b-2507",
  "stepfun-ai/Step-3.7-Flash": "step-3.7-flash",
  "stepfun-ai/step-3.7-flash": "step-3.7-flash",
  "stepfun/step-3.7-flash": "step-3.7-flash",
  "step-flash": "step-3.7-flash",
  "openrouter:stepfun/step-3.7-flash": "step-3.7-flash",
  "zai-org/GLM-4.5-Air": "glm-4.5-air",
  "GLM-4.5-Air": "glm-4.5-air",
  "z-ai/glm-4.5-air": "glm-4.5-air",
  "z-ai:z-ai/glm-4.5-air": "glm-4.5-air",
  "Qwen/Qwen3-14B": "qwen-3-14b",
  "qwen3-14b": "qwen-3-14b",
  "qwen/qwen3-14b": "qwen-3-14b",
  "Qwen/Qwen3-Next-80B-A3B-Instruct": "qwen-3-next-80b-a3b",
  "qwen3-next-80b-a3b": "qwen-3-next-80b-a3b",
  "qwen3-next-80b-a3b-instruct": "qwen-3-next-80b-a3b",
  "qwen/qwen3-next-80b-a3b-instruct": "qwen-3-next-80b-a3b",
  "alibaba:qwen/qwen3-next-80b-a3b-instruct": "qwen-3-next-80b-a3b",
  "Qwen/Qwen2.5-Coder-7B-Instruct": "qwen-2.5-coder-7b",
  "openrouter:qwen/qwen2.5-coder-7b-instruct": "qwen-2.5-coder-7b",
  "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4": "nemotron-3-ultra-550b-a55b-nvfp4",
  "Qwen/Qwen3.5-35B-A3B": "qwen-3.5-35b-a3b",
  "qwen3.5-35b-a3b": "qwen-3.5-35b-a3b",
  "qwen/qwen3.5-35b-a3b": "qwen-3.5-35b-a3b",
  "alibaba:qwen/qwen3.5-35b-a3b": "qwen-3.5-35b-a3b",
  "google/gemma-3-27b-it": "gemma-3-27b-it",
  "openrouter:google/gemma-3-27b-it": "gemma-3-27b-it",
  "google/gemma-3-12b-it": "gemma-3-12b-it",
  "openrouter:google/gemma-3-12b-it": "gemma-3-12b-it",
  "microsoft/phi-4": "phi-4",
  "openrouter:microsoft/phi-4": "phi-4",
  "Qwen/Qwen3-VL-30B-A3B-Instruct": "qwen-3-vl-30b-a3b",
  "qwen3-vl-30b-a3b": "qwen-3-vl-30b-a3b",
  "qwen/qwen3-vl-30b-a3b-instruct": "qwen-3-vl-30b-a3b",
  "openrouter:qwen/qwen3-vl-30b-a3b-instruct": "qwen-3-vl-30b-a3b",
  "prism-ml/Ternary-Bonsai-27B-AWQ-4bit": "ternary-bonsai-27b-awq-4bit",
  "moonshotai/Kimi-K2-Instruct-0905": "kimi-k2-0905",
  "kimi-k2-0905-preview": "kimi-k2-0905",
  "moonshotai/kimi-k2-0905": "kimi-k2-0905",
  "openrouter:moonshotai/kimi-k2-0905": "kimi-k2-0905",
  "Qwen/Qwen2.5-7B-Instruct": "qwen-2.5-7b",
  "hf:Qwen/Qwen2.5-7B-Instruct": "qwen-2.5-7b",
  "qwen/qwen-2.5-7b-instruct": "qwen-2.5-7b",
  "Qwen/Qwen3-VL-235B-A22B-Instruct": "qwen-3-vl-235b-a22b",
  "qwen3-vl-235b-a22b": "qwen-3-vl-235b-a22b",
  "qwen3-vl-235b-a22b-instruct": "qwen-3-vl-235b-a22b",
  "qwen/qwen3-vl-235b-a22b-instruct": "qwen-3-vl-235b-a22b",
  "openrouter:qwen/qwen3-vl-235b-a22b-instruct": "qwen-3-vl-235b-a22b",
  "meta-llama/Llama-3.3-70B-Instruct": "llama-3.3-70b",
  "@cf/meta/llama-3.3-70b-instruct-fp8-fast": "llama-3.3-70b",
  "hf:meta-llama/Llama-3.3-70B-Instruct": "llama-3.3-70b",
  "meta/llama-3.3-70b-instruct": "llama-3.3-70b",
  "meta-llama/llama-3.3-70b-instruct": "llama-3.3-70b",
  "llama": "llama-3.3-70b",
  "Qwen/Qwen3-Coder-480B-A35B-Instruct": "qwen-3-coder-480b-a35b",
  "qwen3-coder-480b-a35b": "qwen-3-coder-480b-a35b",
  "qwen3-coder-480b-a35b-instruct": "qwen-3-coder-480b-a35b",
  "alibaba:qwen/qwen3-coder-480b-a35b-instruct": "qwen-3-coder-480b-a35b",
  "openai/gpt-oss-safeguard-20b": "gpt-oss-safeguard-20b",
  "openrouter:openai/gpt-oss-safeguard-20b": "gpt-oss-safeguard-20b",
  "CohereLabs/c4ai-command-r7b-12-2024": "command-r7b24",
  "command-r7b-12-2024": "command-r7b24",
  "cohere/command-r7b-12-2024": "command-r7b24",
  "Qwen/Qwen3-235B-A22B-Instruct-2507": "qwen-3-235b-a22b-2507",
  "qwen3-235b-a22b-instruct-2507": "qwen-3-235b-a22b-2507",
  "qwen/qwen3-235b-a22b-2507": "qwen-3-235b-a22b-2507",
  "openrouter:qwen/qwen3-235b-a22b-2507": "qwen-3-235b-a22b-2507",
  "meta-llama/Llama-4-Scout-17B-16E-Instruct": "llama-4-scout-17b-16e",
  "llama-4-scout-17b-16e-instruct": "llama-4-scout-17b-16e",
  "stepfun-ai/Step-3.5-Flash": "step-3.5-flash",
  "stepfun-ai/step-3.5-flash": "step-3.5-flash",
  "stepfun/step-3.5-flash": "step-3.5-flash",
  "openrouter:stepfun/step-3.5-flash": "step-3.5-flash",
  "Qwen/Qwen2.5-Coder-3B-Instruct": "qwen-2.5-coder-3b",
  "Sao10K/L3-8B-Stheno-v3.2": "l3-8b-stheno-v3.2",
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B": "deepseek-r1-distill-qwen-7b",
  "meta-llama/Llama-Guard-4-12B": "llama-guard-4-12b",
  "meta/llama-guard-4-12b": "llama-guard-4-12b",
  "meta-llama/llama-guard-4-12b": "llama-guard-4-12b",
  "togetherai:meta-llama/llama-guard-4-12b": "llama-guard-4-12b",
  "Qwen/Qwen3-4B-Thinking-2507": "qwen-3-4b-thinking-2507",
  "zai-org/GLM-4.7": "glm-4.7",
  "GLM-4.7": "glm-4.7",
  "z-ai/glm-4.7": "glm-4.7",
  "Catniti/glm-4.7": "glm-4.7",
  "z-ai:z-ai/glm-4.7": "glm-4.7",
  "aisingapore/Gemma-SEA-LION-v4-27B-IT": "gemma-sea-lion-v4-27b-it",
  "CohereLabs/c4ai-command-a-03-2025": "command-a25",
  "deepseek-ai/DeepSeek-R1-Distill-Llama-8B": "deepseek-r1-distill-llama-8b",
  "openrouter:deepseek/deepseek-r1-distill-llama-8b": "deepseek-r1-distill-llama-8b",
  "swiss-ai/Apertus-8B-Instruct-2509": "apertus-8b-2509",
  "CohereLabs/tiny-aya-global": "tiny-aya-global",
  "Qwen/Qwen3-235B-A22B": "qwen-3-235b-a22b",
  "qwen3-235b-a22b": "qwen-3-235b-a22b",
  "qwen/qwen3-235b-a22b": "qwen-3-235b-a22b",
  "alibaba:qwen/qwen3-235b-a22b": "qwen-3-235b-a22b",
  "speakleash/Bielik-11B-v3.0-Instruct": "bielik-11b-v3.0",
  "CohereLabs/tiny-aya-earth": "tiny-aya-earth",
  "MiniMaxAI/MiniMax-M2.7": "minimax-m2.7",
  "MiniMax-M2.7": "minimax-m2.7",
  "minimaxai/minimax-m2.7": "minimax-m2.7",
  "minimax/minimax-m2.7": "minimax-m2.7",
  "minimax:minimax/minimax-m2.7": "minimax-m2.7",
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8": "llama-4-maverick-17b-128e",
  "meta/llama-4-maverick-17b-128e-instruct": "llama-4-maverick-17b-128e",
  "deepseek-ai/DeepSeek-V3-0324": "deepseek-v3-0324",
  "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT": "ernie-4.5-vl-424b-a47b-base-pt",
  "zai-org/GLM-4-32B-0414": "glm-4-32b-0414",
  "deepseek-ai/DeepSeek-R1-0528": "deepseek-r1-0528",
  "deepseek/deepseek-r1-0528": "deepseek-r1-0528",
  "openrouter:deepseek/deepseek-r1-0528": "deepseek-r1-0528",
  "Qwen/Qwen3-235B-A22B-Thinking-2507": "qwen-3-235b-a22b-thinking-2507",
  "qwen3-235b-a22b-thinking-2507": "qwen-3-235b-a22b-thinking-2507",
  "qwen/qwen3-235b-a22b-thinking-2507": "qwen-3-235b-a22b-thinking-2507",
  "openrouter:qwen/qwen3-235b-a22b-thinking-2507": "qwen-3-235b-a22b-thinking-2507",
  "deepseek-ai/DeepSeek-V3": "deepseek",
  "hf:deepseek-ai/DeepSeek-V3": "deepseek",
  "zai-org/GLM-4.5": "glm-4.5",
  "GLM-4.5": "glm-4.5",
  "z-ai/glm-4.5": "glm-4.5",
  "z-ai:z-ai/glm-4.5": "glm-4.5",
  "zai-org/GLM-4.5V": "glm-4.5v",
  "zai-org/GLM-4.5V-FP8": "glm-4.5v",
  "z-ai/glm-4.5v": "glm-4.5v",
  "z-ai:z-ai/glm-4.5v": "glm-4.5v",
  "alpindale/WizardLM-2-8x22B": "wizardlm-2-8x22b",
  "microsoft/wizardlm-2-8x22b": "wizardlm-2-8x22b",
  "openrouter:microsoft/wizardlm-2-8x22b": "wizardlm-2-8x22b",
  "Qwen/Qwen2.5-72B-Instruct": "qwen-2.5-72b",
  "hf:Qwen/Qwen2.5-72B-Instruct": "qwen-2.5-72b",
  "qwen/qwen-2.5-72b-instruct": "qwen-2.5-72b",
  "zai-org/GLM-4.6": "glm-4.6",
  "z-ai/glm-4.6": "glm-4.6",
  "z-ai:z-ai/glm-4.6": "glm-4.6",
  "zai-org/GLM-4.6V-Flash": "glm-4.6v-flash",
  "MarcosFRG/glm-4.6v-flash": "glm-4.6v-flash",
  "z-ai:z-ai/glm-4.6v-flash": "glm-4.6v-flash",
  "Sao10K/L3-8B-Lunaris-v1": "l3-8b-lunaris",
  "deepseek-ai/DeepSeek-V3.1": "deepseek-v3.1",
  "zai-org/GLM-4.6V-FP8": "glm-4.6v",
  "GLM-4.6V": "glm-4.6v",
  "z-ai/glm-4.6v": "glm-4.6v",
  "z-ai:z-ai/glm-4.6v": "glm-4.6v",
  "MiniMaxAI/MiniMax-M1-80k": "minimax-m1-80k",
  "deepseek-ai/DeepSeek-V3.1-Terminus": "deepseek-v3.1-terminus",
  "deepseek/deepseek-v3.1-terminus": "deepseek-v3.1-terminus",
  "openrouter:deepseek/deepseek-v3.1-terminus": "deepseek-v3.1-terminus",
  "CohereLabs/c4ai-command-r-08-2024": "command-r24",
  "command-r-08-2024": "command-r",
  "cohere/command-r-08-2024": "command-r24",
  "openrouter:cohere/command-r-08-2024": "command-r24",
  "deepseek-ai/DeepSeek-V3.2-Exp": "deepseek-v3.2-exp",
  "deepseek/deepseek-v3.2-exp": "deepseek-v3.2-exp",
  "openrouter:deepseek/deepseek-v3.2-exp": "deepseek-v3.2-exp",
  "CohereLabs/aya-expanse-32b": "aya-expanse-32b",
  "c4ai-aya-expanse-32b": "aya-expanse-32b",
  "CohereLabs/aya-vision-32b": "aya-vision-32b",
  "c4ai-aya-vision-32b": "aya-vision-32b",
  "MiniMaxAI/MiniMax-M2": "minimax-m2",
  "minimax-m2-preview": "minimax-m2",
  "minimax/minimax-m2": "minimax-m2",
  "minimax:minimax/minimax-m2": "minimax-m2",
  "CohereLabs/c4ai-command-r7b-arabic-02-2025": "command-r7b-arabic25",
  "command-r7b-arabic-02-2025": "command-r7b-arabic25",
  "CohereLabs/command-a-vision-07-2025": "command-a-vision25",
  "command-a-vision-07-2025": "command-a-vision25",
  "MiniMaxAI/MiniMax-M2.1": "minimax-m2.1",
  "minimax-m2.1-preview": "minimax-m2.1",
  "minimax/minimax-m2.1": "minimax-m2.1",
  "minimax:minimax/minimax-m2.1": "minimax-m2.1",
  "CohereLabs/command-a-reasoning-08-2025": "command-a-reasoning25",
  "command-a-reasoning-08-2025": "command-a-reasoning25",
  "google/gemma-3n-E4B-it": "gemma-3n-e4b-it",
  "google/gemma-3n-e4b-it": "gemma-3n-e4b-it",
  "togetherai:google/gemma-3n-e4b-it": "gemma-3n-e4b-it",
  "CohereLabs/command-a-translate-08-2025": "command-a-translate25",
  "command-a-translate-08-2025": "command-a-translate25",
  "Qwen/Qwen3-VL-235B-A22B-Thinking": "qwen-3-vl-235b-a22b-thinking",
  "qwen3-vl-235b-a22b-thinking": "qwen-3-vl-235b-a22b-thinking",
  "qwen/qwen3-vl-235b-a22b-thinking": "qwen-3-vl-235b-a22b-thinking",
  "openrouter:qwen/qwen3-vl-235b-a22b-thinking": "qwen-3-vl-235b-a22b-thinking",
  "pearl-ai/Gemma-4-31B-it-pearl": "gemma-4-31b-it-pearl",
  "CohereLabs/tiny-aya-water": "tiny-aya-water",
  "swiss-ai/Apertus-70B-Instruct-2509": "apertus-70b-2509",
  "zai-org/AutoGLM-Phone-9B-Multilingual": "autoglm-phone-9b-multilingual",
  "CohereLabs/tiny-aya-fire": "tiny-aya-fire",
  "aisingapore/Qwen-SEA-LION-v4-32B-IT": "qwen-sea-lion-v4-32b-it",
  "allenai/Olmo-3-7B-Instruct": "olmo-3-7b",
  "utter-project/EuroLLM-22B-Instruct-2512": "eurollm-22b-2512",
  "command-r-plus-08-2024": "command-r-plus24",
  "cohere/command-r-plus-08-2024": "command-r-plus24",
  "openrouter:cohere/command-r-plus-08-2024": "command-r-plus24",
  "default:": "default",
  "Agent Tools (MCP)": "agent-tools",
  "openai/gpt-4o:batch": "gpt-4o",
  "openrouter:openai/gpt-4o:batch": "gpt-4o",
  "openai/gpt-4o-mini:batch": "gpt-4o-mini",
  "openrouter:openai/gpt-4o-mini:batch": "gpt-4o-mini",
  "openrouter:openai/o1": "o1",
  "infron:openai/o1-mini": "o1-mini",
  "openai/o3-mini:batch": "o3-mini",
  "openrouter:openai/o3-mini:batch": "o3-mini",
  "openai/o4-mini:batch": "o4-mini",
  "openrouter:openai/o4-mini:batch": "o4-mini",
  "openai/gpt-4.1:batch": "gpt-4.1",
  "openrouter:openai/gpt-4.1:batch": "gpt-4.1",
  "openai/gpt-4.1-mini:batch": "gpt-4.1-mini",
  "openrouter:openai/gpt-4.1-mini:batch": "gpt-4.1-mini",
  "openai/gpt-4.1-nano:batch": "gpt-4.1-nano",
  "openrouter:openai/gpt-4.1-nano:batch": "gpt-4.1-nano",
  "gpt-4.5-preview": "gpt-4.5",
  "openai/gpt-oss-120b:batch": "gpt-oss-120b",
  "srv_mkom688d57c76d8a3542:openai/gpt-oss-120b": "gpt-oss-120b",
  "llama-3.1-405b-instruct": "llama-3.1-405b",
  "llamascout": "llama-4-scout",
  "srv_mtkdrhxt45fe276b15c0:@cf/mistralai/mistral-small-3.1-24b-instruct": "mistral-small-3.1-24b",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-2.5-flash": "gemini-2.5-flash",
  "google/gemini-2.5-flash:batch": "gemini-2.5-flash",
  "google/gemini-2.5-pro-preview": "gemini-2.5-pro",
  "google/gemini-3.1-pro-preview:batch": "gemini-3.1-pro",
  "openrouter:google/gemini-3.1-pro-preview:batch": "gemini-3.1-pro",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.1-flash-lite-preview": "gemini-3.1-flash-lite",
  "openrouter:google/gemini-3.1-flash-lite:batch": "gemini-3.1-flash-lite",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.6-flash": "gemini-3.6-flash",
  "google/gemini-3.6-flash": "gemini-3.6-flash",
  "google/gemini-3.6-flash:batch": "gemini-3.6-flash",
  "openrouter:google/gemini-3.6-flash:batch": "gemini-3.6-flash",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.7-flash": "gemini-3.7-flash",
  "google/gemini-3.7-flash": "gemini-3.7-flash",
  "google/gemini-3.7-flash:batch": "gemini-3.7-flash",
  "openrouter:google/gemini-3.7-flash:batch": "gemini-3.7-flash",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.8-flash": "gemini-3.8-flash",
  "google/gemini-3.8-flash": "gemini-3.8-flash",
  "google/gemini-3.8-flash:batch": "gemini-3.8-flash",
  "openrouter:google/gemini-3.8-flash:batch": "gemini-3.8-flash",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.5-flash-lite": "gemini-3.5-flash-lite",
  "google/gemini-3.5-flash-lite": "gemini-3.5-flash-lite",
  "google/gemini-3.5-flash-lite:batch": "gemini-3.5-flash-lite",
  "openrouter:google/gemini-3.5-flash-lite:batch": "gemini-3.5-flash-lite",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-3.5-flash": "gemini-3.5-flash",
  "google/gemini-3.5-flash:batch": "gemini-3.5-flash",
  "openrouter:google/gemini-3.5-flash:batch": "gemini-3.5-flash",
  "gemini-flash-lite-latest": "gemini-flash-lite",
  "srv_mrgy0nmbc8a86c407f17:models/gemini-flash-lite-latest": "gemini-flash-lite",
  "qwq-32b-preview": "qwq-32b",
  "deepseek-chat": "deepseek-v3",
  "auto": "grok-3",
  "kimi-k2-instruct": "kimi-k2",
  "deepseek-ai/DeepSeek-V4.1-Flash": "deepseek-v4.1-flash",
  "deepseek/deepseek-v4.1-flash": "deepseek-v4.1-flash",
  "togetherai:deepseek-ai/deepseek-v4.1-flash": "deepseek-v4.1-flash",
  "zai-org/GLM-5.3": "glm-5.3",
  "zai-org/GLM-5.3-BF16": "glm-5.3",
  "srv_mp2huzrg06e426ad12f3:zai-org/GLM-5.3": "glm-5.3",
  "GLM-5.3": "glm-5.3",
  "z-ai/glm-5.3": "glm-5.3",
  "z-ai/glm-5.3:batch": "glm-5.3",
  "z-ai:z-ai/glm-5.3": "glm-5.3",
  "zai-org/GLM-5.3-Flash": "glm-5.3-flash",
  "zai-org/GLM-5.3-Flash-BF16": "glm-5.3-flash",
  "srv_mkombumpae45db46dcb8:z-ai/glm-5.3-flash": "glm-5.3-flash",
  "GLM-5.3-Flash": "glm-5.3-flash",
  "z-ai/glm-5.3-flash": "glm-5.3-flash",
  "z-ai/glm-5.3-flash:batch": "glm-5.3-flash",
  "z-ai:z-ai/glm-5.3-flash": "glm-5.3-flash",
  "moonshotai/Kimi-K3": "kimi-k3",
  "moonshotai/kimi-k3": "kimi-k3",
  "moonshotai/kimi-k3:batch": "kimi-k3",
  "togetherai:moonshotai/kimi-k3": "kimi-k3",
  "Qwen/Qwen3.8-2.4T-A95B": "qwen-3.8-2.4t-a95b",
  "qwen/qwen3.8-2.4t-a95b": "qwen-3.8-2.4t-a95b",
  "qwen/qwen3.8-2.4t-a95b:batch": "qwen-3.8-2.4t-a95b",
  "togetherai:qwen/qwen3.8-2.4t-a95b": "qwen-3.8-2.4t-a95b",
  "deepseek-ai/DeepSeek-V4-Pro-0813": "deepseek-v4-pro-0813",
  "HuggingChat:deepseek-ai/DeepSeek-V4-Pro-0813": "deepseek-v4-pro-0813",
  "deepseek/deepseek-v4-pro-0813": "deepseek-v4-pro-0813",
  "deepseek/deepseek-v4-pro-0813:batch": "deepseek-v4-pro-0813",
  "togetherai:deepseek-ai/deepseek-v4-pro-0813": "deepseek-v4-pro-0813",
  "deepseek-ai/DeepSeek-V4-Flash-0731": "deepseek-v4-flash-0731",
  "srv_mkombumpae45db46dcb8:deepseek-ai/deepseek-v4-flash-0731": "deepseek-v4-flash-0731",
  "deepseek-ai/deepseek-v4-flash-0731": "deepseek-v4-flash-0731",
  "deepseek/deepseek-v4-flash-0731": "deepseek-v4-flash-0731",
  "deepseek/deepseek-v4-flash-0731:batch": "deepseek-v4-flash-0731",
  "togetherai:deepseek-ai/deepseek-v4-flash-0731": "deepseek-v4-flash-0731",
  "srv_monk1pkz433a519ff2be:z-ai/glm-5.2:free": "glm-5.2",
  "z-ai/glm-5.2:free": "glm-5.2",
  "openrouter:moonshotai/kimi-k2.7-code": "kimi-k2.7-code",
  "srv_mp5miql908c8738d71be:community/NamanSoni78/nemotron-3-ultra-550b-a55b": "nemotron-3-ultra-550b-a55b",
  "nvidia/nemotron-3-ultra-550b-a55b": "nemotron-3-ultra-550b-a55b",
  "nvidia/nemotron-3-ultra-550b-a55b:free": "nemotron-3-ultra-550b-a55b",
  "community/NamanSoni78/nemotron-3-ultra-550b-a55b": "nemotron-3-ultra-550b-a55b",
  "openrouter:nvidia/nemotron-3-ultra-550b-a55b:free": "nemotron-3-ultra-550b-a55b",
  "srv_mtsj8uzo97d3c0d49960:deepseek-z/deepseek-v4-flash": "deepseek-v4-flash",
  "deepseek-v4-flash:0731": "deepseek-v4-flash",
  "deepseek-v4-flash-free": "deepseek-v4-flash",
  "deepseek/deepseek-v4-flash-free": "deepseek-v4-flash",
  "openrouter:~deepseek/deepseek-v4-flash-latest": "deepseek-v4-flash",
  "srv_mr9dda21bf67b4c62086:deepseek/deepseek-v4-pro": "deepseek-v4-pro",
  "deepseek-v4-pro:0813": "deepseek-v4-pro",
  "openrouter:deepseek/deepseek-v4-pro": "deepseek-v4-pro",
  "openrouter:moonshotai/kimi-k2.6": "kimi-k2.6",
  "HuggingChat:XiaomiMiMo/MiMo-V2.5-Pro": "mimo-v2.5-pro",
  "openrouter:qwen/qwen3.6-35b-a3b": "qwen-3.6-35b-a3b",
  "openrouter:qwen/qwen3.5-397b-a17b": "qwen-3.5-397b-a17b",
  "google/gemma-4-26b-a4b-it": "gemma-4-26b-a4b-it",
  "openrouter:google/gemma-4-31b-it:free": "gemma-4-31b-it",
  "srv_mkombumpae45db46dcb8:nvidia/nemotron-3-super-120b-a12b": "nemotron-3-super-120b-a12b",
  "nvidia/nemotron-3-super-120b-a12b": "nemotron-3-super-120b-a12b",
  "nvidia/nemotron-3-super-120b-a12b:free": "nemotron-3-super-120b-a12b",
  "openrouter:nvidia/nemotron-3-super-120b-a12b:free": "nemotron-3-super-120b-a12b",
  "qwen3-max-preview": "qwen-3-max",
  "openrouter:qwen/qwen3-max": "qwen-3-max",
  "Qwen/Qwen3.8-27B": "qwen-3.8-27b",
  "qwen3.8-27b": "qwen-3.8-27b",
  "srv_mtsj8uzo97d3c0d49960:openrouter-z/qwen3.8-27b": "qwen-3.8-27b",
  "qwen/qwen3.8-27b": "qwen-3.8-27b",
  "qwen/qwen3.8-27b:free": "qwen-3.8-27b",
  "qwen/qwen3.8-27b-free": "qwen-3.8-27b",
  "openrouter:qwen/qwen3.8-27b:free": "qwen-3.8-27b",
  "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp": "deepseek-v4-flash-vision-exp",
  "srv_mr9dda21bf67b4c62086:deepseek/deepseek-v4-flash-vision-exp": "deepseek-v4-flash-vision-exp",
  "deepseek/deepseek-v4-flash-vision-exp": "deepseek-v4-flash-vision-exp",
  "deepseek/deepseek-v4-flash-vision-exp:batch": "deepseek-v4-flash-vision-exp",
  "openrouter:deepseek/deepseek-v4-flash-vision-exp:batch": "deepseek-v4-flash-vision-exp",
  "HuggingChat:Qwen/Qwen3.5-9B": "qwen-3.5-9b",
  "qwen/qwen3.5-9b:batch": "qwen-3.5-9b",
  "meta-models/Muse-Glimmer-30B": "muse-glimmer-30b",
  "srv_mp5miql908c8738d71be:community/YoannDev90/muse-glimmer-30b:free": "muse-glimmer-30b",
  "meta/muse-glimmer-30b": "muse-glimmer-30b",
  "meta/muse-glimmer-30b:batch": "muse-glimmer-30b",
  "community/YoannDev90/muse-glimmer-30b:free": "muse-glimmer-30b",
  "togetherai:meta-models/muse-glimmer-30b": "muse-glimmer-30b",
  "srv_mkombumpae45db46dcb8:openai/gpt-oss-20b": "gpt-oss-20b",
  "openrouter:openai/gpt-oss-20b": "gpt-oss-20b",
  "inclusionAI/Ling-3.0-flash-VL": "ling-3.0-flash-vl",
  "srv_monk1pkz433a519ff2be:inclusionai/ling-3.0-flash-vl:free": "ling-3.0-flash-vl",
  "inclusionai/ling-3.0-flash-vl": "ling-3.0-flash-vl",
  "inclusionai/ling-3.0-flash-vl:free": "ling-3.0-flash-vl",
  "openrouter:inclusionai/ling-3.0-flash-vl:free": "ling-3.0-flash-vl",
  "inclusionAI/Ling-3.0-flash-Fin": "ling-3.0-flash-fin",
  "inclusionai/ling-3.0-flash-fin:free": "ling-3.0-flash-fin",
  "ling-3.0-flash-fin-free": "ling-3.0-flash-fin",
  "openrouter:inclusionai/ling-3.0-flash-fin:free": "ling-3.0-flash-fin",
  "srv_mtsj8uzo97d3c0d49960:minimax-z/minimax-m3": "minimax-m3",
  "minimax/minimax-m3:batch": "minimax-m3",
  "togetherai:minimaxai/minimax-m3": "minimax-m3",
  "openrouter:qwen/qwen3.6-27b": "qwen-3.6-27b",
  "openrouter:qwen/qwen3-coder-30b-a3b-instruct": "qwen-3-coder-30b-a3b",
  "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16": "nemotron-3.5-lightning-30b-a3b",
  "srv_mkombumpae45db46dcb8:nvidia/nemotron-3.5-lightning-30b-a3b": "nemotron-3.5-lightning-30b-a3b",
  "nvidia/nemotron-3.5-lightning-30b-a3b": "nemotron-3.5-lightning-30b-a3b",
  "inclusionAI/Ling-3.0-flash": "ling-3.0-flash",
  "inclusionai/ling-3.0-flash": "ling-3.0-flash",
  "openrouter:inclusionai/ling-3.0-flash": "ling-3.0-flash",
  "openrouter:qwen/qwen3.5-35b-a3b": "qwen-3.5-35b-a3b",
  "ibm-granite/granite-4.2-3b": "granite-4.2-3b",
  "ibm-granite/granite-4.2-8b": "granite-4.2-8b",
  "openrouter:ibm-granite/granite-4.2-8b": "granite-4.2-8b",
  "thinkingmachines/inkling:free": "inkling",
  "srv_mtkdrhxt45fe276b15c0:@cf/zai-org/glm-4.7-flash": "glm-4.7-flash",
  "openrouter:z-ai/glm-4.7-flash": "glm-4.7-flash",
  "thinkingmachines/Inkling-Small": "inkling-small",
  "thinkingmachines/inkling-small:free": "inkling-small",
  "openrouter:thinkingmachines/inkling-small:free": "inkling-small",
  "srv_mkom688d57c76d8a3542:openai/gpt-oss-safeguard-20b": "gpt-oss-safeguard-20b",
  "openrouter:meta-llama/llama-guard-4-12b": "llama-guard-4-12b",
  "openrouter:moonshotai/kimi-k2.5": "kimi-k2.5",
  "Qwen/Qwen3-30B-A3B": "qwen-3-30b-a3b",
  "qwen3-30b-a3b": "qwen-3-30b-a3b",
  "qwen/qwen3-30b-a3b": "qwen-3-30b-a3b",
  "openrouter:qwen/qwen3-30b-a3b": "qwen-3-30b-a3b",
  "mimo-v2.5-free": "mimo-v2.5",
  "ibm-granite/granite-4.2-30b": "granite-4.2-30b",
  "openrouter:qwen/qwen3.5-122b-a10b": "qwen-3.5-122b-a10b",
  "stepfun/step-3.7-flash:free": "step-3.7-flash",
  "openrouter:qwen/qwen3.5-27b": "qwen-3.5-27b",
  "openrouter:minimax/minimax-m2.7": "minimax-m2.7",
  "tencent/hy3-free": "hy3",
  "openrouter:qwen/qwen3-235b-a22b": "qwen-3-235b-a22b",
  "infron:qwen/qwen3-coder-480b-a35b:priority": "qwen-3-coder-480b-a35b",
  "zai-org/GLM-4.6-FP8": "glm-4.6",
  "openrouter:minimax/minimax-m2.5": "minimax-m2.5",
  "NousResearch/Hermes-3-Llama-3.1-70B": "hermes-3-llama-3.1-70b",
  "nousresearch/hermes-3-llama-3.1-70b": "hermes-3-llama-3.1-70b",
  "openrouter:nousresearch/hermes-3-llama-3.1-70b": "hermes-3-llama-3.1-70b",
  "srv_msu3vtvl920c386aa8a4:deepseek-ai/DeepSeek-V3.1": "deepseek-v3.1",
  "infron:deepseek/deepseek-v3.1": "deepseek-v3.1",
  "openrouter:z-ai/glm-4.5v": "glm-4.5v",
  "openrouter:qwen/qwen3-next-80b-a3b-instruct": "qwen-3-next-80b-a3b",
  "srv_mp5miql908c8738d71be:community/MarcosFRG/glm-4.6v-flash": "glm-4.6v-flash",
  "community/MarcosFRG/glm-4.6v-flash": "glm-4.6v-flash",
  "infron:z-ai/glm-4.6v-flash": "glm-4.6v-flash",
  "openrouter:minimax/minimax-m2": "minimax-m2",
  "openrouter:minimax/minimax-m2.1": "minimax-m2.1",
  "qwen3-vl-30b-a3b-instruct": "qwen-3-vl-30b-a3b",
  "infron:cohere/command-a-03-2025": "command-a25",
  "openrouter:z-ai/glm-4.6v": "glm-4.6v"
}
