package main

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// embedEmptyPlaceholder is the name of an empty placeholder file embedded per
// platform. It lets build tags select the right archive while keeping go:embed
// happy even before fetch-python.sh has run.
const embedEmptyPlaceholder = "EMPTY_PYTHON_RUNTIME"

// embedRuntimeArchive embeds one platform's runtime archive. The actual
// archive is generated by fetch-python.sh and stored under embed/<os>/.
// The variable is declared in the build-tagged files runtime_<os>.go.
// The placeholder file lets `go build` succeed before fetch-python.sh runs.

// ensureRuntime extracts the embedded CPython + g4f runtime to
// ~/.g4f/python-embed if it is missing, then returns the python interpreter
// path. The binary itself stays completely portable — nothing is written next
// to the executable.
func ensureRuntime() (string, error) {
	binDir := installDir()

	// First run: extract and install g4f into the embedded Python.
	stamp := filepath.Join(binDir, ".g4f-runtime", ".installed")
	if !hasEmbeddedZip() {
		// No real runtime baked in — distinguish "not built yet" from a real error.
		markerPath := "embed/" + runtime.GOOS + "/" + embedEmptyPlaceholder
		marker, err := fs.ReadFile(embedRuntimeArchive, markerPath)
		if err == nil && strings.TrimSpace(string(marker)) == "EMPTY_PYTHON_RUNTIME" {
			return "", fmt.Errorf("the Python runtime is not embedded in this build. Build a release with build.sh or run fetch-python.sh first")
		}
		return "", fmt.Errorf("no embedded runtime archive for this platform (run fetch-python.sh and rebuild)")
	}

	exe := pythonExecutable(binDir)
	if _, err := os.Stat(exe); err == nil {
		if _, err := os.Stat(stamp); err == nil {
			return exe, nil // already installed
		}
		return exe, nil
	}

	// Extract the embedded archive next to the binary.
	if err := extractEmbedded(binDir); err != nil {
		return "", err
	}
	// Write the unix launcher (windows uses python.exe from the archive).
	if err := writeLauncher(binDir); err != nil {
		return "", err
	}
	exe = pythonExecutable(binDir)
	if _, err := os.Stat(exe); err != nil {
		return "", fmt.Errorf("python runtime extracted but %s is missing", exe)
	}
	return exe, nil
}

// installDir is the fixed user-level runtime location: ~/.g4f/python-embed.
// This keeps the executable fully relocatable and shares one runtime across
// all g4f-go binaries/versions on the machine.
func installDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".g4f", "python-embed")
}

// hasEmbeddedZip reports whether a real runtime archive is baked into this build.
func hasEmbeddedZip() bool {
	entries, err := embeddedArchives()
	return err == nil && len(entries) > 0
}

// embeddedArchives lists the runtime zips embedded for the current GOOS.
func embeddedArchives() ([]string, error) {
	osDir := "embed/" + runtime.GOOS
	return fs.Glob(embedRuntimeArchive, osDir+"/*.zip")
}

// goArchToken maps runtime.GOARCH to the token used in archive names.
func goArchToken() string {
	switch runtime.GOARCH {
	case "arm64":
		return "arm64"
	case "amd64", "x86_64":
		return "x64"
	case "386", "x86":
		return "x86"
	case "arm":
		return "arm"
	}
	return runtime.GOARCH
}

// pickArchive chooses the embedded zip that matches the host architecture.
// Falls back to a generic x64/amd64 archive (e.g. FreeBSD reuses linux-x64).
func pickArchive(entries []string) string {
	tok := goArchToken()
	for _, e := range entries {
		if strings.Contains(e, tok) {
			return e
		}
	}
	for _, e := range entries {
		if strings.Contains(e, "x64") || strings.Contains(e, "amd64") {
			return e
		}
	}
	return entries[0]
}

// extractEmbedded unpacks embed/<os>/<os>-<arch>-embed-<ver>.zip into the
// user install dir using stdlib archive/zip only (no external tool needed).
func extractEmbedded(binDir string) error {
	// The embed.FS layout mirrors the repo: embed/<os>/<archive>.zip.
	entries, err := embeddedArchives()
	if err != nil || len(entries) == 0 {
		return fmt.Errorf("no embedded runtime archive for this platform (run fetch-python.sh and rebuild)")
	}
	archive := pickArchive(entries)
	src, err := embedRuntimeArchive.Open(archive)
	if err != nil {
		return fmt.Errorf("open embedded archive: %w", err)
	}
	data, err := io.ReadAll(src)
	src.Close()
	if err != nil {
		return fmt.Errorf("read embedded archive: %w", err)
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}
	if err := extractZip(bytes.NewReader(data), int64(len(data)), binDir); err != nil {
		return fmt.Errorf("extract embedded runtime: %w", err)
	}
	return nil
}

// installG4F installs the g4f Python package into the embedded interpreter and
// writes the .installed stamp. Uses the bundled pip via site-packages so no
// network access is required after the release archive was built.
func installG4F(binDir, exe string, start time.Time) error {
	fmt.Printf("Installing gpt4free into the embedded Python runtime...\n")
	code, err := runPython(noSignalCtx(), exe, []string{
		"-m", "pip", "install",
		"--no-input", "g4f[slim]",
	}, pipEnv(binDir)...)
	if err != nil || code != 0 {
		return fmt.Errorf("pip install g4f failed (exit %d): %w", code, err)
	}
	stamp := filepath.Join(binDir, ".g4f-runtime", ".installed")
	if err := os.MkdirAll(filepath.Dir(stamp), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(stamp, []byte("g4f installed"), 0o644); err != nil {
		return err
	}
	fmt.Printf("gpt4free installed in %.1fs\n", time.Since(start).Seconds())
	return nil
}

// pipEnv restricts pip to the embedded runtime so the first run never touches
// the network. A future `g4f-go install g4f --upgrade` can relax this.
func pipEnv(binDir string) []string {
	home := pythonHome(binDir)
	// pbs installs are a full layout: lib/pythonX.Y/site-packages (unix) or
	// Lib/site-packages (windows) inside the interpreter home.
	lib := filepath.Join(home, "Lib", "site-packages")
	if runtime.GOOS != "windows" {
		lib = filepath.Join(home, "lib", "python3.14", "site-packages")
	}
	return []string{
		"PYTHONHOME=" + home,
		"PYTHONNOUSERSITE=1",
		"PYTHONDONTWRITEBYTECODE=1",
		"PYTHONUTF8=1",
		"PYTHONPATH=" + lib,
	}
}
